name: run opencl cts
description: run opencl cts

# This action is not standalone and assumes it has been run after the build_opencl_cts action.

inputs:
  target:
    description: 'target architecture'

runs:
  using: "composite"
  steps:
    - name: Download ock artefact
      uses: actions/download-artifact@v4
      with:
        name: ock_${{inputs.target}}
        path: install_ock

# inputs.cts_profile == ??
# inputs.cities_args == ??

    - name: Run opencl cts
      shell: bash
      env:
        # CTS_CSV_FILE == opencl_conformance_tests_quick.csv || opencl_conformance_tests_full.csv
        CTS_CSV_FILE: opencl_conformance_tests_full.csv
        # CTS_FILTER == cts-3.0-online-ignore-linux-host.csv - needs checkout addition
        CTS_FILTER: cts-3.0-online-ignore-linux-host.csv
        # CTS_TIMEOUT == 18:00:00 - OK on github?
        CTS_TIMEOUT: 18:00:00
      run: |
        ls -lRa * $GITHUB_WORKSPACE && sleep 2
        set -x
        ls -l $GITHUB_WORKSPACE/OpenCL-CTS && sleep 2
        ls -l $GITHUB_WORKSPACE/scripts/testing/run_cities.py && sleep 2
        ls -l $GITHUB_WORKSPACE/OpenCL-CTS/test_conformance && sleep 2
        ls -l $GITHUB_WORKSPACE/install_icd/lib && sleep 2
        ls -l install_ock/bin/clc && sleep 2
        ls -l install_ock/lib/libCL.so && sleep 2
        ls -l $GITHUB_WORKSPACE/OpenCL-CTS/test_conformance/$CTS_CSV_FILE && sleep 2
        ls -l $GITHUB_WORKSPACE/source/cl/scripts/$CTS_FILTER && sleep 2
        set +x

        cd "$GITHUB_WORKSPACE/OpenCL-CTS"
        echo "Running OpenCL CTS tests with CTS file $CTS_CSV_FILE with filter $CTS_FILTER"
        # $[[ inputs.cts_profile ]] - needed?
        # $[[ inputs.cities_args ]] - needed?
        python -u "$GITHUB_WORKSPACE/scripts/testing/run_cities.py" -v --color=always --timeout $CTS_TIMEOUT -b "$GITHUB_WORKSPACE/OpenCL-CTS/test_conformance" -L "$GITHUB_WORKSPACE/install_icd/lib" -e "CLC_EXECUTABLE=install_ock/bin/clc" -e "OCL_ICD_FILENAMES=install_ock/lib/libCL.so" -e "CL_PLATFORM_INDEX=0" -s "$GITHUB_WORKSPACE/OpenCL-CTS/test_conformance/$CTS_CSV_FILE" -i "$GITHUB_WORKSPACE/source/cl/scripts/$CTS_FILTER"

#        cd "$CI_PROJECT_DIR/OpenCL-CTS"
#        echo "Running OpenCL CTS tests with CTS file $CTS_CSV_FILE with filter $CTS_FILTER"
#        python -u "$CI_PROJECT_DIR/oneapi-construction-kit/scripts/testing/run_cities.py" -v
#          --color=always
#          --timeout $CTS_TIMEOUT
#          $[[ inputs.cts_profile ]]
#          $[[ inputs.cities_args ]]
#          -b "$CI_PROJECT_DIR/OpenCL-CTS/test_conformance"
#          -L "$CI_PROJECT_DIR/OpenCL-CTS/lib"
#          -e "CLC_EXECUTABLE=$CA_INSTALL_DIR/bin/clc"
#          -e "OCL_ICD_FILENAMES=$CA_INSTALL_DIR/lib/libCL.so"
#          -e "CL_PLATFORM_INDEX=0"
#          -s "$CI_PROJECT_DIR/OpenCL-CTS/test_conformance/$CTS_CSV_FILE"
#          -i "$CI_PROJECT_DIR/oneapi-construction-kit/source/cl/scripts/$CTS_FILTER"
