name: run opencl cts
description: run opencl cts

# This action is not standalone and assumes it has been run after the build_opencl_cts action.

inputs:
  target:
    description: 'target architecture'
  test_type:
    description: 'quick | full'
    default: "quick"

runs:
  using: "composite"
  steps:
    - name: Download ock artefact
      uses: actions/download-artifact@v4
      with:
        name: ock_${{inputs.target}}
        path: install_ock

    - name: Run opencl cts
      shell: bash
      env:
        CTS_CSV_FILE: opencl_conformance_tests_${{inputs.test_type}}.csv
        # TODO: host-x86_64-linux filter - expand for other targets
        CTS_FILTER: cts-3.0-online-ignore-linux-host.csv
        CTS_TIMEOUT: 18:00:00 # OK for github?
      run: |
        CTS_PROFILE=""
        if [ "${{inputs.target}}" = "host_aarch64_linux" ] ; then \
          CTS_PROFILE="-p qemu --qemu 'qemu-aarch64 -L /usr/aarch64-linux-gnu'"; \
        fi
        cd "$GITHUB_WORKSPACE/OpenCL-CTS"
        echo "Running OpenCL CTS tests with CTS file $CTS_CSV_FILE with filter $CTS_FILTER"
        set -x
        python -u "$GITHUB_WORKSPACE/scripts/testing/run_cities.py" -v \
               --color=always --timeout $CTS_TIMEOUT \
               $CTS_PROFILE \
               -b "$GITHUB_WORKSPACE/test_conformance" \
               -L "$GITHUB_WORKSPACE/install_icd/lib" \
               -e "CLC_EXECUTABLE=$GITHUB_WORKSPACE/install_ock/bin/clc" \
               -e "OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so" \
               -e "CL_PLATFORM_INDEX=0" \
               -s "$GITHUB_WORKSPACE/test_conformance/$CTS_CSV_FILE" \
               -i "$GITHUB_WORKSPACE/source/cl/scripts/$CTS_FILTER"
