name: run opencl cts
description: run opencl cts

# This action is not standalone and assumes it has been run after the build_opencl_cts action.

inputs:
  target:
    description: 'target architecture'
  test_type:
    description: 'quick | full'
    default: "quick"

runs:
  using: "composite"
  steps:
    - name: Download ock artefact
      uses: actions/download-artifact@v4
      with:
        name: ock_${{inputs.target}}
        path: install_ock

    - name: Run opencl cts
      shell: bash
      env:
        CTS_CSV_FILE: opencl_conformance_tests_${{inputs.test_type}}.csv
        # TODO: expand filter for other targets
        CTS_FILTER: cts-3.0-online-ignore-linux-host.csv
        CTS_TIMEOUT: 18:00:00 # OK for github?
      run: |
        cd "$GITHUB_WORKSPACE/OpenCL-CTS"
        echo "Running OpenCL CTS tests with CTS file $CTS_CSV_FILE with filter $CTS_FILTER"
        export QEMU_SETTING=""
        if [[ "${{inputs.target}}" =~ .*aarch64.* ]] ; then
          echo QEMU SETTINGS MATCH FOR ${{inputs.target}}
          QEMU_SETTING="-p qemu --qemu '/usr/bin/qemu-aarch64 -L /usr/aarch64-linux-gnu'"
        fi
        echo python -u $GITHUB_WORKSPACE/scripts/testing/run_cities.py -v \
               --color=always --timeout $CTS_TIMEOUT \
               $QEMU_SETTING \
               -b $GITHUB_WORKSPACE/test_conformance \
               -L $GITHUB_WORKSPACE/install_icd/lib \
               -e CLC_EXECUTABLE=$GITHUB_WORKSPACE/install_ock/bin/clc \
               -e OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so \
               -e CL_PLATFORM_INDEX=0 \
               -s $GITHUB_WORKSPACE/test_conformance/$CTS_CSV_FILE \
               -i $GITHUB_WORKSPACE/source/cl/scripts/$CTS_FILTER
        set -x
        RUN_CITIES="python -u $GITHUB_WORKSPACE/scripts/testing/run_cities.py -v \
          --color=always --timeout $CTS_TIMEOUT \
          $QEMU_SETTING \
          -b $GITHUB_WORKSPACE/test_conformance \
          -L $GITHUB_WORKSPACE/install_icd/lib \
          -e CLC_EXECUTABLE=$GITHUB_WORKSPACE/install_ock/bin/clc \
          -e OCL_ICD_FILENAMES=$GITHUB_WORKSPACE/install_ock/lib/libCL.so \
          -e CL_PLATFORM_INDEX=0 \
          -s $GITHUB_WORKSPACE/test_conformance/$CTS_CSV_FILE \
          -i $GITHUB_WORKSPACE/source/cl/scripts/$CTS_FILTER"
        eval $RUN_CITIES
