name: run opencl cts
description: run opencl cts

# This action is not standalone and assumes it has been run after the build_opencl_cts action.

inputs:
  target:
    description: 'target architecture'

runs:
  using: "composite"
  steps:
    - name: Download ock artefact
      uses: actions/download-artifact@v4
      with:
        name: ock_${{inputs.target}}
        path: install_ock

# CI_PROJECT_DIR == GITHUB_WORKSPACE ??
# CA_INSTALL_DIR == install_ock = note does clc live here? No "bin" in artefact?
# CTS_CSV_FILE == opencl_conformance_tests_quick.csv || opencl_conformance_tests_full.csv
# CTS_FILTER == cts-3.0-online-ignore-linux-host.csv - needs checkout addition
# CTS_TIMEOUT == 18:00:00 - OK on github?
# inputs.cts_profile == ??
# inputs.cities_args == ??

    - name: Run opencl cts
      shell: bash
      run: |
        ls -la * $GITHUB_WORKSPACE
        ls -l $GITHUB_WORKSPACE/install_ock/bin/clc
        ls -l $GITHUB_WORKSPACE/source/cl/scripts/cts-3.0-online-ignore-linux-host.csv
        ls -l $GITHUB_WORKSPACE/scripts/testing/run_cities.py
        ls -l $GITHUB_WORKSPACE/OpenCL-CTS/test_conformance/opencl_conformance_tests_full.csv
        ls -l $GITHUB_WORKSPACE/install_icd/lib
        ls -l $GITHUB_WORKSPACE/install_ock/lib/libCL.so


#        cd "$CI_PROJECT_DIR/OpenCL-CTS"
#        echo "Running OpenCL CTS tests with CTS file $CTS_CSV_FILE with filter $CTS_FILTER"
#        python -u "$CI_PROJECT_DIR/oneapi-construction-kit/scripts/testing/run_cities.py" -v
#          --color=always
#          --timeout $CTS_TIMEOUT
#          $[[ inputs.cts_profile ]]
#          $[[ inputs.cities_args ]]
#          -b "$CI_PROJECT_DIR/OpenCL-CTS/test_conformance"
#          -L "$CI_PROJECT_DIR/OpenCL-CTS/lib"
#          -e "CLC_EXECUTABLE=$CA_INSTALL_DIR/bin/clc"
#          -e "OCL_ICD_FILENAMES=$CA_INSTALL_DIR/lib/libCL.so"
#          -e "CL_PLATFORM_INDEX=0"
#          -s "$CI_PROJECT_DIR/OpenCL-CTS/test_conformance/$CTS_CSV_FILE"
#          -i "$CI_PROJECT_DIR/oneapi-construction-kit/source/cl/scripts/$CTS_FILTER"
