name: run tornado
description: run tornado

# This action is not standalone and assumes it has been run after the build_tornado action
# and that the icd is already installed at install_icd
inputs:
  target:
    description: 'target architecture'

runs:
  using: "composite"
  steps:
    - name: Download ock artefact
      uses: actions/download-artifact@v4
      with:
        name: ock_${{inputs.target}}
        path: install_ock

    - name: Run tornado example
      shell: bash
      run: |
        export ARTEFACT_CHECKOUT_PATH=$GITHUB_WORKSPACE/install_ock
        export ICD_LOADER_INSTALL_PATH=$GITHUB_WORKSPACE/install_icd

        export LD_LIBRARY_PATH=$ICD_LOADER_INSTALL_PATH/lib:$LD_LIBRARY_PATH
        echo $LD_LIBRARY_PATH
        export OCL_ICD_FILENAMES=$ARTEFACT_CHECKOUT_PATH/lib/libCL.so
        export JAVA_HOME=`readlink -f $(command -v java) | sed 's/\/bin\/java//'`
        export TORNADO_SDK=$GITHUB_WORKSPACE/TornadoVM_build/bin/sdk
        export PATH=$TORNADO_SDK/bin:$PATH
        
        git clone https://github.com/beehive-lab/TornadoVM.git -b develop --depth 1
        cd TornadoVM
        CA_HOST_DUMP_ASM=1 tornado --printKernel --threadInfo -m tornado.examples/uk.ac.manchester.tornado.examples.compute.MatrixMultiplication2D 256
