// Copyright (C) Codeplay Software Limited. All Rights Reserved.
#ifndef MULTI_LLVM_LLVM_VERSION_H_INCLUDED
#define MULTI_LLVM_LLVM_VERSION_H_INCLUDED

#include <llvm/Config/llvm-config.h>

#define LLVM_VERSION_EQUAL(MAJOR, MINOR) \
  (LLVM_VERSION_MAJOR == (MAJOR) && LLVM_VERSION_MINOR == (MINOR))

#define LLVM_VERSION_LESS(MAJOR, MINOR) \
  ((LLVM_VERSION_MAJOR < (MAJOR)) ||    \
   (LLVM_VERSION_MAJOR == (MAJOR) && LLVM_VERSION_MINOR < (MINOR)))

#define LLVM_VERSION_LESS_EQUAL(MAJOR, MINOR) \
  (LLVM_VERSION_EQUAL(MAJOR, MINOR) || LLVM_VERSION_LESS(MAJOR, MINOR))

#define LLVM_VERSION_GREATER(MAJOR, MINOR) \
  ((LLVM_VERSION_MAJOR > (MAJOR)) ||       \
   (LLVM_VERSION_MAJOR == (MAJOR) && LLVM_VERSION_MINOR > (MINOR)))

#define LLVM_VERSION_GREATER_EQUAL(MAJOR, MINOR) \
  (LLVM_VERSION_EQUAL(MAJOR, MINOR) || LLVM_VERSION_GREATER(MAJOR, MINOR))

#endif  // MULTI_LLVM_LLVM_VERSION_H_INCLUDED
