LIBRARY ${ExportLibraryName}
EXPORTS
  clGetPlatformIDs
  clGetPlatformInfo
  clGetDeviceIDs
  clGetDeviceInfo
  clCreateSubDevices
  clRetainDevice
  clReleaseDevice
  clCreateContext
  clCreateContextFromType
  clRetainContext
  clReleaseContext
  clGetContextInfo
  clCreateCommandQueue
  clRetainCommandQueue
  clReleaseCommandQueue
  clGetCommandQueueInfo
  clCreateBuffer
  clCreateSubBuffer
  clCreateImage
  clRetainMemObject
  clReleaseMemObject
  clGetSupportedImageFormats
  clGetMemObjectInfo
  clGetImageInfo
  clSetMemObjectDestructorCallback
  clCreateSampler
  clRetainSampler
  clReleaseSampler
  clGetSamplerInfo
  clCreateProgramWithSource
  clCreateProgramWithBinary
  clCreateProgramWithBuiltInKernels
  clRetainProgram
  clReleaseProgram
  clBuildProgram
  clCompileProgram
  clLinkProgram
  clUnloadPlatformCompiler
  clGetProgramInfo
  clGetProgramBuildInfo
  clCreateKernel
  clCreateKernelsInProgram
  clRetainKernel
  clReleaseKernel
  clSetKernelArg
  clGetKernelInfo
  clGetKernelArgInfo
  clGetKernelWorkGroupInfo
  clWaitForEvents
  clGetEventInfo
  clCreateUserEvent
  clRetainEvent
  clReleaseEvent
  clSetUserEventStatus
  clSetEventCallback
  clGetEventProfilingInfo
  clFlush
  clFinish
  clEnqueueReadBuffer
  clEnqueueReadBufferRect
  clEnqueueWriteBuffer
  clEnqueueWriteBufferRect
  clEnqueueFillBuffer
  clEnqueueCopyBuffer
  clEnqueueCopyBufferRect
  clEnqueueReadImage
  clEnqueueWriteImage
  clEnqueueFillImage
  clEnqueueCopyImage
  clEnqueueCopyImageToBuffer
  clEnqueueCopyBufferToImage
  clEnqueueMapBuffer
  clEnqueueMapImage
  clEnqueueUnmapMemObject
  clEnqueueMigrateMemObjects
  clEnqueueNDRangeKernel
  clEnqueueTask
  clEnqueueNativeKernel
  clEnqueueMarkerWithWaitList
  clEnqueueBarrierWithWaitList
  clGetExtensionFunctionAddressForPlatform
  clCreateImage2D
  clCreateImage3D
  clEnqueueMarker
  clEnqueueWaitForEvents
  clEnqueueBarrier
  clUnloadCompiler
  clGetExtensionFunctionAddress
  clSetCommandQueueProperty
  ; Conditionalize the following?
  clIcdGetPlatformIDsKHR
  ; Required for debuggers to detect jitted code
  @LLVM_DEBUG_REGISTER_CODE_SYM@
  @LLVM_DEBUG_DESCRIPTOR_SYM@
  @IS_300@clSetKernelArgSVMPointer
  @IS_300@clSVMAlloc
  @IS_300@clSVMFree
  @IS_300@clEnqueueSVMFree
  @IS_300@clEnqueueSVMMap
  @IS_300@clEnqueueSVMUnmap
  @IS_300@clEnqueueSVMMemcpy
  @IS_300@clEnqueueSVMMemFill
  @IS_300@clCreateCommandQueueWithProperties
  @IS_300@clCreatePipe
  @IS_300@clGetPipeInfo
  @IS_300@clCreateSamplerWithProperties
  @IS_300@clSetKernelExecInfo
  @IS_300@clGetKernelSubGroupInfo
  @IS_300@clCreateProgramWithIL
  @IS_300@clGetHostTimer
  @IS_300@clGetDeviceAndHostTimer
  @IS_300@clEnqueueSVMMigrateMem
  @IS_300@clCloneKernel
  @IS_300@clSetDefaultDeviceCommandQueue
  @IS_300@clSetProgramSpecializationConstant
  @IS_300@clSetProgramReleaseCallback
  @IS_300@clSetContextDestructorCallback
  @IS_300@clCreateBufferWithProperties
  @IS_300@clCreateImageWithProperties
