name: build_pr_windows_msvc_x86_64_llvm_latest_cl3_0_offline
description: Build pr windows_msvc_x86_64_llvm_latest_cl3_0_offline

inputs:
  cache_seed:
    type: boolean
    default: false
  is_pull_request:
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: remove any old dirs
      shell: bash  
      run:
        rm -rf build build_offline install_offline

    - name: build ock x86_64
      uses: ./.github/actions/do_build_ock
      with:
        build_targets: ${{ inputs.cache_seed == 'true' && 'UnitCL clc' || 'check-ock' }}
        builtin_kernel: ON
        shell_to_use: pwsh
        gtest_launcher: "python3;-u;${{ github.workspace }}/scripts/gtest-terse-runner.py"
        debug_support: ON
        enable_unitcl_expensive: ${{ !inputs.is_pull_request && 'ON' || 'OFF' }}
        offline_kernel_tests: ${{ inputs.cache_seed == 'true' && 'OFF' || 'ON' }}

    - name: build ock x86_64 offline
      uses: ./.github/actions/do_build_ock
      with:
        build_targets: ${{ inputs.cache_seed == 'true' && 'UnitCL' || 'check-ock' }}
        runtime_compiler_enabled: OFF
        external_clc: "${{ github.workspace }}/build/bin/clc.exe"
        shell_to_use: pwsh
        gtest_launcher: "python3;-u;${{ github.workspace }}/scripts/gtest-terse-runner.py"
        debug_support: ON
        install_dir: ${{ github.workspace }}/install_offline
        build_dir: ${{ github.workspace }}/build_offline
        offline_kernel_tests: ${{ inputs.cache_seed == 'true' && 'OFF' || 'ON' }}
