name: build sycl cts
description: build sycl cts

inputs:
  target:
    description: 'target architecture'

runs:
  using: "composite"
  steps:
    - name: calc vars
      id: calc_vars
      uses: ./.github/actions/calc_vars
      with:
        target: ${{ inputs.target }}  

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main

    - name: download icd artifact
      uses: actions/download-artifact@v4
      with:
        name: icd_${{inputs.target}}
        path: install_icd

    - name: download headers artifact
      uses: actions/download-artifact@v4
      with:
        name: header_${{inputs.target}}
        path: install_headers

    - name: download dpc++ artifact
      uses: actions/download-artifact@v4
      with:
        name: dpcpp_${{inputs.target}}
        path: install_dpcpp

    - name: unpackage artifacts # package/unpackage avoids known 'permissions loss' issue
      shell: bash
      run: |
        cd install_dpcpp
        echo LISTING
        ls -la
        tar xf dpcpp.tar
        rm dpcpp.tar
        echo LISTING
        ls -la

    - name: checkout sycl cts
      uses: actions/checkout@v4
      with:
        repository: KhronosGroup/SYCL-CTS
        path: SYCL-CTS.src
        submodules: true

    - name: build SYCL CTS
      shell: bash
      run: |
        echo calling cmake and ninja on SYCL CTS
        # Todo: as we extend into cross etc, we may want to expand on the cxx flags
        # We build SYCL-CTS without installing it, so build directly in the top level.
        git -C SYCL-CTS.src log -1
        # git -C SYCL-CTS.src apply $CI_PROJECT_DIR/patches/SYCL-CTS-0002-Permit-building-for-unknown-architectures.patch
        # TODO: REMOVE EXCLUSIONS
        # build only accessor_basic for now
        printf "accessor_generic\naccessor_legacy\naccessor_placeholder\naddress_space\natomic\natomic_fence\natomic_ref\natomic_ref_stress\nbit_cast\nbuffer\ncommon\ncontext\ncuda_interop\ndevice\ndevice_event\ndevice_selector\nerror\nevent\nexception_handling\nexceptions\nextension\nfull_feature_set\nfunction_objects\ngroup\ngroup_functions\nh_item\nhandler\nheader\nhierarchical\nhost_accessor\nhost_task\nid\nimage\nimage_accessor\ninvoke\nis_device_copyable\nitem\nkernel\nkernel_args\nkernel_bundle\nlanguage\nlocal_accessor\nmarray_arithmetic_assignment\nmarray_arithmetic_binary\nmarray_basic\nmarray_bitwise\nmarray_pre_post\nmarray_relational\nmath_builtin_api\nmulti_ptr\nnamespace\nnd_item\nnd_range\nopencl_interop\noptional_kernel_features\nplatform\npointers\nproperty\nqueue\nrange\nreduction\nsampler\nscalars\nspec_constants\nstream\nsub_group\nsycl_external\nusm\nvector_alias\nvector_api\nvector_constructors\nvector_deduction_guides\nvector_load_store\nvector_operators\nvector_swizzle_assignment\nvector_swizzles\n" > $GITHUB_WORKSPACE/EXCLUSIONS
        cmake -S SYCL-CTS.src \
            -GNinja \
            -B SYCL-CTS \
            -DSYCL_IMPLEMENTATION=DPCPP \
            -DDPCPP_INSTALL_DIR=$GITHUB_WORKSPACE/install_dpcpp \
            -DOpenCL_LIBRARY=$GITHUB_WORKSPACE/install_icd/lib/libOpenCL.so \
            -DOpenCL_INCLUDE_DIR=$GITHUB_WORKSPACE/install_headers/include \
            -DCMAKE_CXX_COMPILER="$GITHUB_WORKSPACE/install_dpcpp/bin/clang++" \
            -DCMAKE_CXX_FLAGS="--target=${{steps.calc_vars.outputs.arch}}-linux-gnu" \
            -DCMAKE_CXX_LINK_FLAGS="-fuse-ld=lld" \
            -DSYCL_CTS_EXCLUDE_TEST_CATEGORIES=$GITHUB_WORKSPACE/EXCLUSIONS
        ninja -C SYCL-CTS -v -j8 -k 0 || :
        #TODO: fyi this made no difference: ninja -C SYCL-CTS -v -l 2.5 -k 0 || :

    - name: upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: sycl_cts_${{inputs.target}}
        path: SYCL-CTS/bin/**
        retention-days: 1
  
