name: build sycl cts
description: build sycl cts

inputs:
  target:
    description: 'target architecture'

runs:
  using: "composite"
  steps:
    - name: calc vars
      id: calc_vars
      uses: ./.github/actions/calc_vars
      with:
        target: ${{ inputs.target }}  

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main

    - name: download icd artifact
      uses: actions/download-artifact@v4
      with:
        name: icd_${{inputs.target}}
        path: install_icd

    - name: download headers artifact
      uses: actions/download-artifact@v4
      with:
        name: header_${{inputs.target}}
        path: install_headers

    - name: download dpc++ artifact
      uses: actions/download-artifact@v4
      with:
        name: dpcpp_${{inputs.target}}
        path: install_dpcpp

    - name: unpackage artifacts # package/unpackage avoids known 'permissions loss' issue
      shell: bash
      run: |
        cd install_dpcpp
        echo LISTING
        ls -la
        tar xf dpcpp.tar
        rm dpcpp.tar
        echo LISTING
        ls -la

    - name: checkout sycl cts
      uses: actions/checkout@v4
      with:
        repository: KhronosGroup/SYCL-CTS
        path: SYCL-CTS.src
        submodules: true

    - name: build SYCL CTS
      shell: bash
      run: |
        echo calling cmake and ninja on SYCL CTS
        # Todo: as we extend into cross etc, we may want to expand on the cxx flags
        # We build SYCL-CTS without installing it, so build directly in the top level.
        git -C SYCL-CTS.src log -1
        # git -C SYCL-CTS.src apply $CI_PROJECT_DIR/patches/SYCL-CTS-0002-Permit-building-for-unknown-architectures.patch
        echo "test_accessor_basic test/accessor_generic accessor_legacy accessor_placeholder address_space atomic atomic_fence atomic_ref atomic_ref_stress bit_cast buffer common context cuda_interop device device_event device_selector error event exception_handling exceptions extension full_feature_set function_objects group group_functions h_item handler header hierarchical host_accessor host_task id image image_accessor invoke is_device_copyable item kernel kernel_args kernel_bundle language local_accessor marray_arithmetic_assignment marray_arithmetic_binary marray_basic marray_bitwise marray_pre_post marray_relational math_builtin_api multi_ptr namespace nd_item nd_range opencl_interop optional_kernel_features platform pointers property queue range reduction sampler scalars spec_constants stream sub_group sycl_external usm vector_alias vector_api vector_constructors vector_deduction_guides vector_load_store vector_operators vector_swizzle_assignment vector_swizzles" > $GITHUB_WORKSPACE/EXCLUSIONS
        # TODO: Remove exclusions
        cmake -S SYCL-CTS.src \
            -GNinja \
            -B SYCL-CTS \
            -DSYCL_IMPLEMENTATION=DPCPP \
            -DDPCPP_INSTALL_DIR=$GITHUB_WORKSPACE/install_dpcpp \
            -DOpenCL_LIBRARY=$GITHUB_WORKSPACE/install_icd/lib/libOpenCL.so \
            -DOpenCL_INCLUDE_DIR=$GITHUB_WORKSPACE/install_headers/include \
            -DCMAKE_CXX_COMPILER="$GITHUB_WORKSPACE/install_dpcpp/bin/clang++" \
            -DCMAKE_CXX_FLAGS="--target=${{steps.calc_vars.outputs.arch}}-linux-gnu" \
            -DCMAKE_CXX_LINK_FLAGS="-fuse-ld=lld" \
            -DSYCL_CTS_EXCLUDE_TEST_CATEGORIES=$GITHUB_WORKSPACE/EXCLUSIONS
        #ninja -C SYCL-CTS -v -j8 -k 0 || :
        ninja -C SYCL-CTS -v -l 2.5 -k 0 || :

    - name: upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: sycl_cts_${{inputs.target}}
        path: SYCL-CTS/bin/**
        retention-days: 1
  
