name: build run sanitizers
description: build run sanitizers

inputs:
  san_type:
    description: 'sanitizer type: tsan OR aubsan'
    type: string
    required: true
  part_id:
    description: 'tests are long-running so split into 2 parts - indicate which to run: part1 OR part2'
    type: string
    required: true
  ubuntu_version:
    description: 'Version of ubuntu used'
    default: 22.04
  llvm_branch:
    description: 'The actual llvm branch to check out e.g. release/20.x'
    type: string
    required: true

runs:
  using: "composite"
  steps:

    - name: Set sanitizer vars
      id: sanitizer_vars
      shell: 'bash'
      run: |
        if [ "${{ inputs.san_type }}" = "tsan" ]; then
           echo "build_type=SanitizeThread" >> "$GITHUB_OUTPUT"
           echo "ninja_options=-j2" >> "$GITHUB_OUTPUT"
           echo "extended_checks=-DCA_ENABLE_EXTENDED_CHECKS=OFF" >> "$GITHUB_OUTPUT"
        else # aubsan
           echo "build_type=SanitizeAddress,Undefined" >> "$GITHUB_OUTPUT"
           echo "ninja_options=-j2" >> "$GITHUB_OUTPUT"
           echo "extended_checks=" >> "$GITHUB_OUTPUT"
        fi
        if [ "${{ inputs.part_id }}" = "part1" ]; then
           echo "build_target=check-ock" >> "$GITHUB_OUTPUT"
           echo "disable_unitcl_vecz_checks=-DCA_CL_DISABLE_UNITCL_VECZ_CHECKS=ON" >> "$GITHUB_OUTPUT"
        else # part2
           echo "build_target=check-ock-UnitCL-group-vecz" >> "$GITHUB_OUTPUT"
           echo "disable_unitcl_vecz_checks=-DCA_CL_DISABLE_UNITCL_VECZ_CHECKS=OFF" >> "$GITHUB_OUTPUT"
        fi
        cat $GITHUB_OUTPUT

    - name: Install clang
      shell: 'bash'
      env:
        UBUNTU_NAME: "${{ inputs.ubuntu_version == '24.04' && 'noble' || 'jammy' }}"
      run: |
        echo "deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/$UBUNTU_NAME/ llvm-toolchain-$UBUNTU_NAME-20 main" | sudo tee /etc/apt/sources.list.d/llvm.list >/dev/null
        sudo apt-get update
        sudo apt-get install -y clang-20

    - name: Checkout llvm/llvm-project
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: ${{ inputs.llvm_branch }}
        path: external/llvm-project

    - name: Build llvm
      shell: 'bash'
      run: |
        echo Build LLVM
        cd external
        cmake llvm-project/llvm \
            -GNinja \
            -Bbuild \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/external/llvm_install \
            -DCA_LLVM_PROJECT_DIR=$GITHUB_WORKSPACE/external/llvm-project \
            -DCA_LLVM_SPIRV_PROJECT_DIR=$GITHUB_WORKSPACE/external/llvm-spirv \
            -DLLVM_ENABLE_ZLIB=FALSE \
            -DLLVM_ENABLE_Z3_SOLVER=FALSE \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DLLVM_USE_SANITIZER=Thread \
            -DLLVM_BUILD_LLVM_DYLIB=ON \
            -DLLVM_LINK_LLVM_DYLIB=ON \
            -DLLVM_ENABLE_DIA_SDK=OFF \
            -DLLVM_ENABLE_ZSTD=FALSE \
            -DLLVM_ENABLE_PROJECTS="clang;lld" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=/usr/bin/clang-20 \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++-20
        echo Install LLVM
        cmake --build $GITHUB_WORKSPACE/external/build --target install -- -j2
        rm -rf $GITHUB_WORKSPACE/external/build

    - name: Build OCK
      shell: 'bash'
      run: |
        echo Build OCK
        cmake \
            -Bbuild \
            -GNinja \
            -DCA_ENABLE_HOST_IMAGE_SUPPORT=OFF \
            -DOCL_EXTENSION_cl_khr_command_buffer=ON \
            -DOCL_EXTENSION_cl_khr_command_buffer_mutable_dispatch=ON \
            ${{ steps.sanitizer_vars.outputs.extended_checks }} \
            ${{ steps.sanitizer_vars.outputs.disable_unitcl_vecz_checks }} \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install \
            -DCA_LLVM_INSTALL_DIR=$GITHUB_WORKSPACE/external/llvm_install \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCA_USE_SANITIZER=Thread \
            -DCMAKE_C_COMPILER=/usr/bin/clang-20 \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++-20 \
            -DCA_ENABLE_DEBUG_SUPPORT=ON \
            -DCA_BUILTINS_TOOLS_DIR=$GITHUB_WORKSPACE/external/llvm_install/bin \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCA_GTEST_LAUNCHER="/usr/bin/python3;-u;$GITHUB_WORKSPACE/scripts/gtest-terse-runner.py" \
            .
        echo Build OCK all config=${{ steps.sanitizer_vars.outputs.build_type }}
        cmake --build $GITHUB_WORKSPACE/build --target all --config ${{ steps.sanitizer_vars.outputs.build_type }}

    - name: Test OCK
      shell: 'bash'
      run: |
        echo Test OCK ninja
        ninja -C build ${{ steps.sanitizer_vars.outputs.ninja_options }} ${{ steps.sanitizer_vars.outputs.build_target }}
