// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan %p/op_any_bvec2.spv -o %t
// RUN: %filecheck < %t %t.pp

#version 450

void main() {
  bvec2 vec = bvec2(true, true);
  bool result = any(vec);
}

// CHECK: ; ModuleID = '{{.*}}'

// CHECK: define spir_kernel void @main() {
// CHECK: %vec = alloca <2 x i1>
// CHECK: %result = alloca i1
// CHECK-GE15: store <2 x i1> <i1 true, i1 true>, ptr %vec
// CHECK-LT15: store <2 x i1> <i1 true, i1 true>, <2 x i1>* %vec
// CHECK-GE15: [[load:%[a-zA-Z0-9]+]] = load <2 x i1>, ptr %vec
// CHECK-LT15: [[load:%[a-zA-Z0-9]+]] = load <2 x i1>, <2 x i1>* %vec
// CHECK: [[sext:%[a-zA-Z0-9]+]] = sext <2 x i1> [[load]] to <2 x i32>
// CHECK: [[call:%[a-zA-Z0-9]+]] = call spir_func i32 @_Z3anyDv2_i(<2 x i32> [[sext]])
// CHECK: [[trunc:%[a-zA-Z0-9]+]] = trunc i32 [[call]] to i1
// CHECK-GE15: store i1 [[trunc]], ptr %result
// CHECK-LT15: store i1 [[trunc]], i1* %result
// CHECK: ret void
// CHECK: }

// CHECK: declare spir_func i32 @_Z3anyDv2_i(<2 x i32>)
