// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan %p/op_function_parameter_bool.spv -o %t
// RUN: %filecheck < %t %t.pp

#version 450

bool foo(bool a, bool b){ 
  return a == b;
}

void main() {
  bool res = foo(true, true);
}

// CHECK: ; ModuleID = '{{.*}}'

// CHECK: define spir_kernel void @main() {
// CHECK: [[res:%[a-zA-Z0-9]+]] = alloca i1
// CHECK: [[param:%[a-zA-Z0-9]+]] = alloca i1
// CHECK: [[param1:%[a-zA-Z0-9]+]] = alloca i1
// CHECK-GE15: store i1 true, ptr [[param]]
// CHECK-LT15: store i1 true, i1* [[param]]
// CHECK-GE15: store i1 true, ptr [[param1]]
// CHECK-LT15: store i1 true, i1* [[param1]]
// CHECK-GE15: [[call:%[a-zA-Z0-9]+]] = call spir_func i1 @{{(foo|"foo\(.+")}}(ptr [[param]], ptr [[param1]])
// CHECK-LT15: [[call:%[a-zA-Z0-9]+]] = call spir_func i1 @{{(foo|"foo\(.+")}}(i1* [[param]], i1* [[param1]])
// CHECK-GE15: store i1 [[call]], ptr [[res]]
// CHECK-LT15: store i1 [[call]], i1* [[res]]
// CHECK: ret void
// CHECK: }

// CHECK-GE15: define private spir_func i1 @{{(foo|"foo\(.+")}}(ptr %a, ptr %b) {
// CHECK-LT15: define private spir_func i1 @{{(foo|"foo\(.+")}}(i1* %a, i1* %b) {
// CHECK-GE15: [[a:%[a-zA-Z0-9]+]] = load i1, ptr %a
// CHECK-LT15: [[a:%[a-zA-Z0-9]+]] = load i1, i1* %a
// CHECK-GE15: [[b:%[a-zA-Z0-9]+]] = load i1, ptr %b
// CHECK-LT15: [[b:%[a-zA-Z0-9]+]] = load i1, i1* %b
// CHECK: [[ret:%[a-zA-Z0-9]+]] = icmp eq i1 [[a]], [[b]]
// CHECK: ret i1 [[ret]]
// CHECK: }
