// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %p/op_fdiv_two_mat3x3_float_operands.spv -o %t
// RUN: %filecheck < %t %s

#version 450

void main() {
  mat3x3 a = {
      {42.42, 42.42, 42.42},
      {42.42, 42.42, 42.42},
      {42.42, 42.42, 42.42}
  };
  mat3x3 b = {
      {42.42, 42.42, 42.42},
      {42.42, 42.42, 42.42},
      {42.42, 42.42, 42.42}
  };
  mat3x3 c = a / b;
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main()
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [3 x <3 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 0
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [3 x <3 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 0
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = fdiv <3 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [3 x <3 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 1
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [3 x <3 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 1
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = fdiv <3 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [3 x <3 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 2
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [3 x <3 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 2
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = fdiv <3 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: [[INITIAL:%[a-zA-Z0-9_]+]] = insertvalue [3 x <3 x float>] undef, <3 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 0
// CHECK: [[INSERT1:%[a-zA-Z0-9_]+]] = insertvalue [3 x <3 x float>] [[INITIAL]], <3 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 1
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = insertvalue [3 x <3 x float>] [[INSERT1]], <3 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 2
// CHECK: ret void
