// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan %p/op_glsl_PackSnorm2x16_vec2.spv -o %t
// RUN: %filecheck < %t %t.pp

// CHECK: ; ModuleID = '{{.*}}'
#version 450

layout (std430, set=0, binding=0) buffer inA {
  vec2 arg0;
};

layout (std430, set=0, binding=1) buffer outR {
  uint res;
};

void main() {
// CHECK-GE15: define spir_kernel void @main(ptr addrspace(1){{( %0)?}}, ptr addrspace(1){{( %1)?}}, ptr addrspace(1){{( %2)?}}) {
// CHECK-LT15: define spir_kernel void @main([[inA:%[a-zA-Z0-9]+]] addrspace(1)*{{( %0)?}}, [[outR:%[a-zA-Z0-9]+]] addrspace(1)*{{( %1)?}}, i32 addrspace(1)*{{( %2)?}}) {
// CHECK-GE15:   [[arg0:%[a-zA-Z0-9]+]] = getelementptr [[inA:%.*]], ptr addrspace(1) {{%[a-zA-Z0-9]+}}, i32 0, i32 0
// CHECK-LT15:   [[arg0:%[a-zA-Z0-9]+]] = getelementptr [[inA]], [[inA]] addrspace(1)* {{%[a-zA-Z0-9]+}}, i32 0, i32 0
// CHECK-GE15:   [[arg9value:%[a-zA-Z0-9]+]] = load <2 x float>, ptr addrspace(1) [[arg0]]
// CHECK-LT15:   [[arg9value:%[a-zA-Z0-9]+]] = load <2 x float>, <2 x float> addrspace(1)* [[arg0]]
  res = packSnorm2x16(arg0);
// CHECK:   [[call:%[a-zA-Z0-9]+]] = call spir_func i32 @_Z13packSnorm2x16Dv2_f(<2 x float> [[arg9value]])
// CHECK-GE15:   [[res:%[a-zA-Z0-9]+]] = getelementptr [[outR:%.*]], ptr addrspace(1) {{%[a-zA-Z0-9]+}}, i32 0, i32 0
// CHECK-LT15:   [[res:%[a-zA-Z0-9]+]] = getelementptr [[outR]], [[outR]] addrspace(1)* {{%[a-zA-Z0-9]+}}, i32 0, i32 0
// CHECK-GE15:   store i32 [[call]], ptr addrspace(1) [[res]]
// CHECK-LT15:   store i32 [[call]], i32 addrspace(1)* [[res]]
// CHECK:   ret void
}
// CHECK: }
