# Copyright (C) Codeplay Software Limited. All Rights Reserved.
set(UVK_GLSL_FILES
  kts_array_spec.comp
  kts_array_spec_op.comp
  kts_image.comp,
  kts_sampler.comp,
  kts_sgemm.comp,
  kts_sgemm_spec.comp
  kts_uniform_outside_main.comp
  kts_workgroup_spec.comp
  kts_workgroup_spec_mixed.comp
  op_glsl_Acos_float.comp
  op_glsl_Acosh_float.comp
  op_glsl_Acosh_vec2.comp
  op_glsl_Acosh_vec3.comp
  op_glsl_Acosh_vec4.comp
  op_glsl_Acos_vec2.comp
  op_glsl_Acos_vec3.comp
  op_glsl_Acos_vec4.comp
  op_glsl_Asin_float.comp
  op_glsl_Asinh_float.comp
  op_glsl_Asinh_vec2.comp
  op_glsl_Asinh_vec3.comp
  op_glsl_Asinh_vec4.comp
  op_glsl_Asin_vec2.comp
  op_glsl_Asin_vec3.comp
  op_glsl_Asin_vec4.comp
  op_glsl_Atan2_float_float.comp
  op_glsl_Atan2_vec2_vec2.comp
  op_glsl_Atan2_vec3_vec3.comp
  op_glsl_Atan2_vec4_vec4.comp
  op_glsl_Atan_float.comp
  op_glsl_Atanh_float.comp
  op_glsl_Atanh_vec2.comp
  op_glsl_Atanh_vec3.comp
  op_glsl_Atanh_vec4.comp
  op_glsl_Atan_vec2.comp
  op_glsl_Atan_vec3.comp
  op_glsl_Atan_vec4.comp
  op_glsl_Barrier.comp
  op_glsl_Ceil_double.comp
  op_glsl_Ceil_dvec2.comp
  op_glsl_Ceil_dvec3.comp
  op_glsl_Ceil_dvec4.comp
  op_glsl_Ceil_float.comp
  op_glsl_Ceil_vec2.comp
  op_glsl_Ceil_vec3.comp
  op_glsl_Ceil_vec4.comp
  op_glsl_Cos_float.comp
  op_glsl_Cosh_float.comp
  op_glsl_Cosh_vec2.comp
  op_glsl_Cosh_vec3.comp
  op_glsl_Cosh_vec4.comp
  op_glsl_Cos_vec2.comp
  op_glsl_Cos_vec3.comp
  op_glsl_Cos_vec4.comp
  op_glsl_Cross_dvec3_dvec3.comp
  op_glsl_Cross_vec3_vec3.comp
  op_glsl_Degrees_float.comp
  op_glsl_Degrees_vec2.comp
  op_glsl_Degrees_vec3.comp
  op_glsl_Degrees_vec4.comp
  op_glsl_Determinant_dmat2.comp
  op_glsl_Determinant_dmat3.comp
  op_glsl_Determinant_dmat4.comp
  op_glsl_Determinant_mat2.comp
  op_glsl_Determinant_mat3.comp
  op_glsl_Determinant_mat4.comp
  op_glsl_Distance_double_double.comp
  op_glsl_Distance_dvec2_dvec2.comp
  op_glsl_Distance_dvec3_dvec3.comp
  op_glsl_Distance_dvec4_dvec4.comp
  op_glsl_Distance_float_float.comp
  op_glsl_Distance_vec2_vec2.comp
  op_glsl_Distance_vec3_vec3.comp
  op_glsl_Distance_vec4_vec4.comp
  op_glsl_Exp2_float.comp
  op_glsl_Exp2_vec2.comp
  op_glsl_Exp2_vec3.comp
  op_glsl_Exp2_vec4.comp
  op_glsl_Exp_float.comp
  op_glsl_Exp_vec2.comp
  op_glsl_Exp_vec3.comp
  op_glsl_Exp_vec4.comp
  op_glsl_FAbs_double.comp
  op_glsl_FAbs_dvec2.comp
  op_glsl_FAbs_dvec3.comp
  op_glsl_FAbs_dvec4.comp
  op_glsl_FAbs_float.comp
  op_glsl_FAbs_vec2.comp
  op_glsl_FAbs_vec3.comp
  op_glsl_FAbs_vec4.comp
  op_glsl_FaceForward_double_double_double.comp
  op_glsl_FaceForward_dvec2_dvec2_dvec2.comp
  op_glsl_FaceForward_dvec3_dvec3_dvec3.comp
  op_glsl_FaceForward_dvec4_dvec4_dvec4.comp
  op_glsl_FaceForward_float_float_float.comp
  op_glsl_FaceForward_vec2_vec2_vec2.comp
  op_glsl_FaceForward_vec3_vec3_vec3.comp
  op_glsl_FaceForward_vec4_vec4_vec4.comp
  op_glsl_FClamp_double_double_double.comp
  op_glsl_FClamp_dvec2_dvec2_dvec2.comp
  op_glsl_FClamp_dvec3_dvec3_dvec3.comp
  op_glsl_FClamp_dvec4_dvec4_dvec4.comp
  op_glsl_FClamp_float_float_float.comp
  op_glsl_FClamp_vec2_vec2_vec2.comp
  op_glsl_FClamp_vec3_vec3_vec3.comp
  op_glsl_FClamp_vec4_vec4_vec4.comp
  op_glsl_FindILsb_int.comp
  op_glsl_FindILsb_ivec2.comp
  op_glsl_FindILsb_ivec3.comp
  op_glsl_FindILsb_ivec4.comp
  op_glsl_FindILsb_uint.comp
  op_glsl_FindILsb_uvec2.comp
  op_glsl_FindILsb_uvec3.comp
  op_glsl_FindILsb_uvec4.comp
  op_glsl_FindSMsb_int.comp
  op_glsl_FindSMsb_ivec2.comp
  op_glsl_FindSMsb_ivec3.comp
  op_glsl_FindSMsb_ivec4.comp
  op_glsl_FindUMsb_uint.comp
  op_glsl_FindUMsb_uvec2.comp
  op_glsl_FindUMsb_uvec3.comp
  op_glsl_FindUMsb_uvec4.comp
  op_glsl_Floor_double.comp
  op_glsl_Floor_dvec2.comp
  op_glsl_Floor_dvec3.comp
  op_glsl_Floor_dvec4.comp
  op_glsl_Floor_float.comp
  op_glsl_Floor_vec2.comp
  op_glsl_Floor_vec3.comp
  op_glsl_Floor_vec4.comp
  op_glsl_Fma_double_double_double.comp
  op_glsl_Fma_dvec2_dvec2_dvec2.comp
  op_glsl_Fma_dvec3_dvec3_dvec3.comp
  op_glsl_Fma_dvec4_dvec4_dvec4.comp
  op_glsl_Fma_float_float_float.comp
  op_glsl_Fma_vec2_vec2_vec2.comp
  op_glsl_Fma_vec3_vec3_vec3.comp
  op_glsl_Fma_vec4_vec4_vec4.comp
  op_glsl_FMax_double_double.comp
  op_glsl_FMax_dvec2_dvec2.comp
  op_glsl_FMax_dvec3_dvec3.comp
  op_glsl_FMax_dvec4_dvec4.comp
  op_glsl_FMax_float_float.comp
  op_glsl_FMax_vec2_vec2.comp
  op_glsl_FMax_vec3_vec3.comp
  op_glsl_FMax_vec4_vec4.comp
  op_glsl_FMin_double_double.comp
  op_glsl_FMin_dvec2_dvec2.comp
  op_glsl_FMin_dvec3_dvec3.comp
  op_glsl_FMin_dvec4_dvec4.comp
  op_glsl_FMin_float_float.comp
  op_glsl_FMin_vec2_vec2.comp
  op_glsl_FMin_vec3_vec3.comp
  op_glsl_FMin_vec4_vec4.comp
  op_glsl_FMix_double_double_double.comp
  op_glsl_FMix_dvec2_dvec2_dvec2.comp
  op_glsl_FMix_dvec3_dvec3_dvec3.comp
  op_glsl_FMix_dvec4_dvec4_dvec4.comp
  op_glsl_FMix_float_float_float.comp
  op_glsl_FMix_vec2_vec2_vec2.comp
  op_glsl_FMix_vec3_vec3_vec3.comp
  op_glsl_FMix_vec4_vec4_vec4.comp
  op_glsl_Fract_double.comp
  op_glsl_Fract_dvec2.comp
  op_glsl_Fract_dvec3.comp
  op_glsl_Fract_dvec4.comp
  op_glsl_Fract_float.comp
  op_glsl_Fract_vec2.comp
  op_glsl_Fract_vec3.comp
  op_glsl_Fract_vec4.comp
  op_glsl_FSign_double.comp
  op_glsl_FSign_dvec2.comp
  op_glsl_FSign_dvec3.comp
  op_glsl_FSign_dvec4.comp
  op_glsl_FSign_float.comp
  op_glsl_FSign_vec2.comp
  op_glsl_FSign_vec3.comp
  op_glsl_FSign_vec4.comp
  op_glsl_InverseSqrt_double.comp
  op_glsl_InverseSqrt_dvec2.comp
  op_glsl_InverseSqrt_dvec3.comp
  op_glsl_InverseSqrt_dvec4.comp
  op_glsl_InverseSqrt_float.comp
  op_glsl_InverseSqrt_vec2.comp
  op_glsl_InverseSqrt_vec3.comp
  op_glsl_InverseSqrt_vec4.comp
  op_glsl_Ldexp_double_int.comp
  op_glsl_Ldexp_dvec2_ivec2.comp
  op_glsl_Ldexp_dvec3_ivec3.comp
  op_glsl_Ldexp_dvec4_ivec4.comp
  op_glsl_Ldexp_float_int.comp
  op_glsl_Ldexp_vec2_ivec2.comp
  op_glsl_Ldexp_vec3_ivec3.comp
  op_glsl_Ldexp_vec4_ivec4.comp
  op_glsl_Length_double.comp
  op_glsl_Length_dvec2.comp
  op_glsl_Length_dvec3.comp
  op_glsl_Length_dvec4.comp
  op_glsl_Length_float.comp
  op_glsl_Length_vec2.comp
  op_glsl_Length_vec3.comp
  op_glsl_Length_vec4.comp
  op_glsl_Log2_float.comp
  op_glsl_Log2_vec2.comp
  op_glsl_Log2_vec3.comp
  op_glsl_Log2_vec4.comp
  op_glsl_Log_float.comp
  op_glsl_Log_vec2.comp
  op_glsl_Log_vec3.comp
  op_glsl_Log_vec4.comp
  op_glsl_MatrixInverse_dmat2.comp
  op_glsl_MatrixInverse_dmat3.comp
  op_glsl_MatrixInverse_dmat4.comp
  op_glsl_MatrixInverse_mat2.comp
  op_glsl_MatrixInverse_mat3.comp
  op_glsl_MatrixInverse_mat4.comp
  op_glsl_Normalize_double.comp
  op_glsl_Normalize_dvec2.comp
  op_glsl_Normalize_dvec3.comp
  op_glsl_Normalize_dvec4.comp
  op_glsl_Normalize_float.comp
  op_glsl_Normalize_vec2.comp
  op_glsl_Normalize_vec3.comp
  op_glsl_Normalize_vec4.comp
  op_glsl_PackDouble2x32_uvec2.comp
  op_glsl_PackHalf2x16_vec2.comp
  op_glsl_PackSnorm2x16_vec2.comp
  op_glsl_PackSnorm4x8_vec4.comp
  op_glsl_PackUnorm2x16_vec2.comp
  op_glsl_PackUnorm4x8_vec4.comp
  op_glsl_Pow_float_float.comp
  op_glsl_Pow_vec2_vec2.comp
  op_glsl_Pow_vec3_vec3.comp
  op_glsl_Pow_vec4_vec4.comp
  op_glsl_Radians_float.comp
  op_glsl_Radians_vec2.comp
  op_glsl_Radians_vec3.comp
  op_glsl_Radians_vec4.comp
  op_glsl_Reflect_double_double.comp
  op_glsl_Reflect_dvec2_dvec2.comp
  op_glsl_Reflect_dvec3_dvec3.comp
  op_glsl_Reflect_dvec4_dvec4.comp
  op_glsl_Reflect_float_float.comp
  op_glsl_Reflect_vec2_vec2.comp
  op_glsl_Reflect_vec3_vec3.comp
  op_glsl_Reflect_vec4_vec4.comp
  op_glsl_Refract_double_double_double.comp
  op_glsl_Refract_dvec2_dvec2_double.comp
  op_glsl_Refract_dvec3_dvec3_double.comp
  op_glsl_Refract_dvec4_dvec4_double.comp
  op_glsl_Refract_float_float_float.comp
  op_glsl_Refract_vec2_vec2_float.comp
  op_glsl_Refract_vec3_vec3_float.comp
  op_glsl_Refract_vec4_vec4_float.comp
  op_glsl_Round_double.comp
  op_glsl_Round_dvec2.comp
  op_glsl_Round_dvec3.comp
  op_glsl_Round_dvec4.comp
  op_glsl_RoundEven_double.comp
  op_glsl_RoundEven_dvec2.comp
  op_glsl_RoundEven_dvec3.comp
  op_glsl_RoundEven_dvec4.comp
  op_glsl_RoundEven_float.comp
  op_glsl_RoundEven_vec2.comp
  op_glsl_RoundEven_vec3.comp
  op_glsl_RoundEven_vec4.comp
  op_glsl_Round_float.comp
  op_glsl_Round_vec2.comp
  op_glsl_Round_vec3.comp
  op_glsl_Round_vec4.comp
  op_glsl_SAbs_int.comp
  op_glsl_SAbs_ivec2.comp
  op_glsl_SAbs_ivec3.comp
  op_glsl_SAbs_ivec4.comp
  op_glsl_SClamp_int_int_int.comp
  op_glsl_SClamp_ivec2_ivec2_ivec2.comp
  op_glsl_SClamp_ivec3_ivec3_ivec3.comp
  op_glsl_SClamp_ivec4_ivec4_ivec4.comp
  op_glsl_Sin_float.comp
  op_glsl_Sinh_float.comp
  op_glsl_Sinh_vec2.comp
  op_glsl_Sinh_vec3.comp
  op_glsl_Sinh_vec4.comp
  op_glsl_Sin_vec2.comp
  op_glsl_Sin_vec3.comp
  op_glsl_Sin_vec4.comp
  op_glsl_SMax_int_int.comp
  op_glsl_SMax_ivec2_ivec2.comp
  op_glsl_SMax_ivec3_ivec3.comp
  op_glsl_SMax_ivec4_ivec4.comp
  op_glsl_SMin_int_int.comp
  op_glsl_SMin_ivec2_ivec2.comp
  op_glsl_SMin_ivec3_ivec3.comp
  op_glsl_SMin_ivec4_ivec4.comp
  op_glsl_SmoothStep_double_double_double.comp
  op_glsl_SmoothStep_dvec2_dvec2_dvec2.comp
  op_glsl_SmoothStep_dvec3_dvec3_dvec3.comp
  op_glsl_SmoothStep_dvec4_dvec4_dvec4.comp
  op_glsl_SmoothStep_float_float_float.comp
  op_glsl_SmoothStep_vec2_vec2_vec2.comp
  op_glsl_SmoothStep_vec3_vec3_vec3.comp
  op_glsl_SmoothStep_vec4_vec4_vec4.comp
  op_glsl_Sqrt_double.comp
  op_glsl_Sqrt_dvec2.comp
  op_glsl_Sqrt_dvec3.comp
  op_glsl_Sqrt_dvec4.comp
  op_glsl_Sqrt_float.comp
  op_glsl_Sqrt_vec2.comp
  op_glsl_Sqrt_vec3.comp
  op_glsl_Sqrt_vec4.comp
  op_glsl_SSign_int.comp
  op_glsl_SSign_ivec2.comp
  op_glsl_SSign_ivec3.comp
  op_glsl_SSign_ivec4.comp
  op_glsl_Step_double_double.comp
  op_glsl_Step_dvec2_dvec2.comp
  op_glsl_Step_dvec3_dvec3.comp
  op_glsl_Step_dvec4_dvec4.comp
  op_glsl_Step_float_float.comp
  op_glsl_Step_vec2_vec2.comp
  op_glsl_Step_vec3_vec3.comp
  op_glsl_Step_vec4_vec4.comp
  op_glsl_Tan_float.comp
  op_glsl_Tanh_float.comp
  op_glsl_Tanh_vec2.comp
  op_glsl_Tanh_vec3.comp
  op_glsl_Tanh_vec4.comp
  op_glsl_Tan_vec2.comp
  op_glsl_Tan_vec3.comp
  op_glsl_Tan_vec4.comp
  op_glsl_Transpose_mat3_toRow.comp
  op_glsl_Transpose_mat3x2_toRow.comp
  op_glsl_Trunc_double.comp
  op_glsl_Trunc_dvec2.comp
  op_glsl_Trunc_dvec3.comp
  op_glsl_Trunc_dvec4.comp
  op_glsl_Trunc_float.comp
  op_glsl_Trunc_vec2.comp
  op_glsl_Trunc_vec3.comp
  op_glsl_Trunc_vec4.comp
  op_glsl_UClamp_uint_uint_uint.comp
  op_glsl_UClamp_uvec2_uvec2_uvec2.comp
  op_glsl_UClamp_uvec3_uvec3_uvec3.comp
  op_glsl_UClamp_uvec4_uvec4_uvec4.comp
  op_glsl_UMax_uint_uint.comp
  op_glsl_UMax_uvec2_uvec2.comp
  op_glsl_UMax_uvec3_uvec3.comp
  op_glsl_UMax_uvec4_uvec4.comp
  op_glsl_UMin_uint_uint.comp
  op_glsl_UMin_uvec2_uvec2.comp
  op_glsl_UMin_uvec3_uvec3.comp
  op_glsl_UMin_uvec4_uvec4.comp
  op_glsl_UnpackDouble2x32_double.comp
  op_glsl_UnpackHalf2x16_uint.comp
  op_glsl_UnpackSnorm2x16_uint.comp
  op_glsl_UnpackSnorm4x8_uint.comp
  op_glsl_UnpackUnorm2x16_uint.comp
  op_glsl_UnpackUnorm4x8_uint.comp)
