// Copyright (C) Codeplay Software Limited. All Rights Reserved.

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout(local_size_x = 1, local_size_y = 1) in;
layout(set = 0, binding = 0, rgba32f) uniform readonly image2D inputImage;
layout(set = 0, binding = 1) buffer out_buffer { vec4 mat_Out[]; };

void main() {
  vec4 rgba = imageLoad(
      inputImage, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y));
  mat_Out[gl_GlobalInvocationID.y * gl_NumWorkGroups.x +
          gl_GlobalInvocationID.x] = rgba;
}
