// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#version 450

layout(local_size_x_id = 0, local_size_y = 2, local_size_z_id = 1) in;

layout(set = 0, binding = 0) buffer in_buffer { float in_buf[]; };
layout(set = 0, binding = 1) buffer out_buffer { float out_buf[]; };

void main() {
  uint id = gl_WorkGroupID.x * gl_WorkGroupSize.x * gl_WorkGroupSize.y *
                gl_WorkGroupSize.z +
            gl_LocalInvocationIndex;
  out_buf[id] = in_buf[id];
}
