# Copyright (C) Codeplay Software Limited. All Rights Reserved.
set(UVK_SPVASM_FILES
  op_glsl_Fma_No_Contraction_float_float_float.spvasm
  op_glsl_Fma_No_Contraction_vec2_vec2_vec2.spvasm
  op_glsl_Fma_No_Contraction_vec3_vec3_vec3.spvasm
  op_glsl_Fma_No_Contraction_vec4_vec4_vec4.spvasm
  op_glsl_Fma_No_Contraction_double_double_double.spvasm
  op_glsl_Fma_No_Contraction_dvec2_dvec2_dvec2.spvasm
  op_glsl_Fma_No_Contraction_dvec3_dvec3_dvec3.spvasm
  op_glsl_Fma_No_Contraction_dvec4_dvec4_dvec4.spvasm
  op_glsl_FrexpStruct_double.spvasm
  op_glsl_FrexpStruct_float.spvasm
  op_glsl_FrexpStruct_vec2.spvasm
  op_glsl_FrexpStruct_vec3.spvasm
  op_glsl_FrexpStruct_vec4.spvasm
  op_glsl_FrexpStruct_dvec2.spvasm
  op_glsl_FrexpStruct_dvec3.spvasm
  op_glsl_FrexpStruct_dvec4.spvasm
  op_glsl_Frexp_double_intPtr.spvasm
  op_glsl_Frexp_float_intPtr.spvasm
  op_glsl_Frexp_vec2_ivec2Ptr.spvasm
  op_glsl_Frexp_vec3_ivec3Ptr.spvasm
  op_glsl_Frexp_vec4_ivec4Ptr.spvasm
  op_glsl_Frexp_dvec2_ivec2Ptr.spvasm
  op_glsl_Frexp_dvec3_ivec3Ptr.spvasm
  op_glsl_Frexp_dvec4_ivec4Ptr.spvasm
  op_glsl_ModfStruct_double.spvasm
  op_glsl_ModfStruct_float.spvasm
  op_glsl_ModfStruct_vec2.spvasm
  op_glsl_ModfStruct_vec3.spvasm
  op_glsl_ModfStruct_vec4.spvasm
  op_glsl_ModfStruct_dvec2.spvasm
  op_glsl_ModfStruct_dvec3.spvasm
  op_glsl_ModfStruct_dvec4.spvasm
  op_glsl_Modf_double_doublePtr.spvasm
  op_glsl_Modf_float_floatPtr.spvasm
  op_glsl_Modf_vec2_vec2Ptr.spvasm
  op_glsl_Modf_vec3_vec3Ptr.spvasm
  op_glsl_Modf_vec4_vec4Ptr.spvasm
  op_glsl_Modf_dvec2_dvec2Ptr.spvasm
  op_glsl_Modf_dvec3_dvec3Ptr.spvasm
  op_glsl_Modf_dvec4_dvec4Ptr.spvasm
  op_glsl_Refract_double_double_float.spvasm
  op_glsl_Refract_dvec2_dvec2_float.spvasm
  op_glsl_Refract_dvec3_dvec3_float.spvasm
  op_glsl_Refract_dvec4_dvec4_float.spvasm
  op_glsl_NClamp_float_float_float.spvasm
  op_glsl_NClamp_vec2_vec2_vec2.spvasm
  op_glsl_NClamp_vec3_vec3_vec3.spvasm
  op_glsl_NClamp_vec4_vec4_vec4.spvasm
  op_glsl_NClamp_double_double_double.spvasm
  op_glsl_NClamp_dvec2_dvec2_dvec2.spvasm
  op_glsl_NClamp_dvec3_dvec3_dvec3.spvasm
  op_glsl_NClamp_dvec4_dvec4_dvec4.spvasm
  op_glsl_NMin_float_float.spvasm
  op_glsl_NMin_vec2_vec2.spvasm
  op_glsl_NMin_vec3_vec3.spvasm
  op_glsl_NMin_vec4_vec4.spvasm
  op_glsl_NMin_double_double.spvasm
  op_glsl_NMin_dvec2_dvec2.spvasm
  op_glsl_NMin_dvec3_dvec3.spvasm
  op_glsl_NMin_dvec4_dvec4.spvasm
  op_glsl_NMax_float_float.spvasm
  op_glsl_NMax_vec2_vec2.spvasm
  op_glsl_NMax_vec3_vec3.spvasm
  op_glsl_NMax_vec4_vec4.spvasm
  op_glsl_NMax_double_double.spvasm
  op_glsl_NMax_dvec2_dvec2.spvasm
  op_glsl_NMax_dvec3_dvec3.spvasm
  op_glsl_NMax_dvec4_dvec4.spvasm
  op_glsl_Quantize_float.spvasm
  op_glsl_Quantize_vec2.spvasm
  op_glsl_Quantize_vec3.spvasm
  op_glsl_Quantize_vec4.spvasm)
