name: install ubuntu cross compilation tools
description: install ubuntu tools needed for cross compilation

inputs:
  cross_arch:
    description: 'target architecture - default is no cross arch'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install ubuntu prerequisites
      shell: bash
      run: |
        if [ "${{ inputs.cross_arch }}" = "x86" ]; then \
            sudo apt-get install --yes gcc-multilib g++-multilib libc6-dev:i386 lib32tinfo-dev; \
        fi
        if [ "${{ inputs.cross_arch }}" = "arm" ]; then \
            sudo apt-get install --yes gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf; \
        fi
        if [ "${{ inputs.cross_arch }}" = "aarch64" ]; then \
            sudo apt-get install --yes gcc-aarch64-linux-gnu g++-aarch64-linux-gnu; \
        fi
        if [ "${{ inputs.cross_arch }}" = "riscv64" ]; then \
            sudo apt-get install --yes gcc-riscv64-linux-gnu g++-riscv64-linux-gnu; \
        fi

