// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan %spv_file_s | FileCheck %s

#version 450

ivec2 func_call_ret_vec2_int() {
  ivec2 a = ivec2(-42, -42);
  return a;
}

void main() {
  ivec2 a = func_call_ret_vec2_int();
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() #0 {
// CHECK: {{[%@].*}} = alloca <2 x i32>
// CHECK: {{[%@].*}} = call spir_func <2 x i32> @{{("func_call_ret_vec2_int.+")}}()
// CHECK: store <2 x i32> {{[%@].*}}, ptr {{[%@].*}}
// CHECK: ret void
// CHECK: define private spir_func <2 x i32> @{{("func_call_ret_vec2_int.+")}}()
// CHECK: {{[%@].*}} = alloca <2 x i32>
// CHECK: store <2 x i32> <i32 -42, i32 -42>, ptr {{[%@].*}}
// CHECK: {{[%@].*}} = load <2 x i32>, ptr {{[%@].*}}
// CHECK: ret <2 x i32> {{[%@].*}}
