// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan %p/func_call_ret_vec3_bool.spv -o %t
// RUN: %filecheck < %t %t.pp

#version 450

bvec3 func_call_ret_vec3_bool() {
  bvec3 a = bvec3(true, true, true);
  return a;
}

void main() {
  bvec3 a = func_call_ret_vec3_bool();
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = alloca <3 x i1>
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = call spir_func <3 x i1> @{{("func_call_ret_vec3_bool.+")}}()
// CHECK-GE15: store <3 x i1> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, ptr {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK-LT15: store <3 x i1> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, <3 x i1>* {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: ret void
// CHECK: define private spir_func <3 x i1> @{{("func_call_ret_vec3_bool.+")}}()
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = alloca <3 x i1>
// CHECK-GE15: store <3 x i1> <i1 true, i1 true, i1 true>, ptr {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK-LT15: store <3 x i1> <i1 true, i1 true, i1 true>, <3 x i1>* {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK-GE15: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <3 x i1>, ptr {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK-LT15: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <3 x i1>, <3 x i1>* {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: ret <3 x i1> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
