// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan %spv_file_s | FileCheck %s

#version 450

bvec4 func_call_ret_vec4_bool() {
  bvec4 a = bvec4(true, true, true, true);
  return a;
}

void main() {
  bvec4 a = func_call_ret_vec4_bool();
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() #0 {
// CHECK: = alloca <4 x i1>
// CHECK: = call spir_func <4 x i1> @{{("func_call_ret_vec4_bool.+")}}()
// CHECK: store <4 x i1> {{[%@].*}}, ptr {{[%@].*}}
// CHECK: ret void
// CHECK: define private spir_func <4 x i1> @{{("func_call_ret_vec4_bool.+")}}()
// CHECK: = alloca <4 x i1>
// CHECK: store <4 x i1> <i1 true, i1 true, i1 true, i1 true>, ptr {{[%@].*}}
// CHECK: = load <4 x i1>, ptr {{[%@].*}}
// CHECK: ret <4 x i1> {{[%@].*}}
