// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %p/func_call_ret_vec4_bool.spv | %filecheck %s

#version 450

bvec4 func_call_ret_vec4_bool() {
  bvec4 a = bvec4(true, true, true, true);
  return a;
}

void main() {
  bvec4 a = func_call_ret_vec4_bool();
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = alloca <4 x i1>
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = call spir_func <4 x i1> @{{("func_call_ret_vec4_bool.+")}}()
// CHECK: store <4 x i1> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, ptr {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: ret void
// CHECK: define private spir_func <4 x i1> @{{("func_call_ret_vec4_bool.+")}}()
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = alloca <4 x i1>
// CHECK: store <4 x i1> <i1 true, i1 true, i1 true, i1 true>, ptr {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <4 x i1>, ptr {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: ret <4 x i1> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
