// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

#version 450

layout (set=0, binding=0) buffer block {
  int a;
  bool[] runtime_array;
};

void main() {
  int result = runtime_array.length();
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main(ptr addrspace(1){{( %0)?}}, ptr addrspace(1){{( %1)?}}) {
// CHECK: [[result:%[a-zA-Z0-9]+]] = alloca i32
// CHECK: [[result_a_ptr:%[a-zA-Z0-9]+]] = getelementptr i32, ptr addrspace(1) {{%[a-zA-Z0-9]+}}, i32 0
// CHECK: [[result_a:%[a-zA-Z0-9]+]] = load i32, ptr addrspace(1) %3
// CHECK: [[result_a_sub:%[a-zA-Z0-9]+]] = sub i32 [[result_a]], 4
// CHECK: [[result_a_div:%[a-zA-Z0-9]+]] = udiv i32 [[result_a_sub]], {{4|8}}
// CHECK: store i32 [[result_a_div]], ptr [[result]]
// CHECK: ret void
