// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

#version 450

void main() {
  bvec2 vec = bvec2(true, true);
  bool result = any(vec);
}

// CHECK: ; ModuleID = '{{.*}}'

// CHECK: define spir_kernel void @main() {
// CHECK: %vec = alloca <2 x i1>
// CHECK: %result = alloca i1
// CHECK: store <2 x i1> <i1 true, i1 true>, ptr %vec
// CHECK: [[load:%[a-zA-Z0-9]+]] = load <2 x i1>, ptr %vec
// CHECK: [[sext:%[a-zA-Z0-9]+]] = sext <2 x i1> [[load]] to <2 x i32>
// CHECK: [[call:%[a-zA-Z0-9]+]] = call spir_func i32 @_Z3anyDv2_i(<2 x i32> [[sext]])
// CHECK: [[trunc:%[a-zA-Z0-9]+]] = trunc i32 [[call]] to i1
// CHECK: store i1 [[trunc]], ptr %result
// CHECK: ret void
// CHECK: }

// CHECK: declare spir_func i32 @_Z3anyDv2_i(<2 x i32>)
