// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan -c Float64 %p/op_array_length_double.spv | %filecheck %s

#version 450

layout (set=0, binding=0) buffer block {
  int a;
  double[] runtime_array;
};

void main() {
  int result = runtime_array.length();
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main(ptr addrspace(1){{( %0)?}}, ptr addrspace(1){{( %1)?}}) {
// CHECK: [[result:%[a-zA-Z0-9]+]] = alloca i32
// CHECK: [[result_a_ptr:%[a-zA-Z0-9]+]] = getelementptr i32, ptr addrspace(1) {{%[a-zA-Z0-9]+}}, i32 0
// CHECK: [[result_a:%[a-zA-Z0-9]+]] = load i32, ptr addrspace(1) %3
// CHECK: [[result_a_sub:%[a-zA-Z0-9]+]] = sub i32 [[result_a]], 4
// CHECK: [[result_a_div:%[a-zA-Z0-9]+]] = udiv i32 [[result_a_sub]], {{4|8}}
// CHECK: store i32 [[result_a_div]], ptr [[result]]
// CHECK: ret void
