// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan -c Float64 %spv_file_s | FileCheck %s

#version 450

void main() {
  int a = -42;
  double b = double(a);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() #0 {
// CHECK: {{[%@].*}} = alloca i32
// CHECK: {{[%@].*}} = alloca double
// CHECK: store i32 -42, ptr {{[%@].*}}
// CHECK: {{[%@].*}} = load i32, ptr {{[%@].*}}
// CHECK: {{[%@].*}} = call spir_func double @_Z14convert_doublei(i32 %1)
// CHECK: store double {{[%@].*}}, ptr {{[%@].*}}
// CHECK: ret void
