// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan -c Float64 %p/op_convert_dvec4_to_ivec4.spv -o %t
// RUN: %filecheck < %t %t.pp

#version 450

void main() {
  dvec4 a = dvec4(-42.42, -42.42, -42.42, -42.42);
  ivec4 b = ivec4(a);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: [[FROM:%[a-zA-Z0-9_]+]] = alloca <4 x double>
// CHECK: [[TO:%[a-zA-Z0-9_]+]] = alloca <4 x i32>
// CHECK-GE15: store <4 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr [[FROM]]
// CHECK-LT15: store <4 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, <4 x double>* [[FROM]]
// CHECK-GE15: {{%[a-zA-Z0-9_]+}} = load <4 x double>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK-LT15: {{%[a-zA-Z0-9_]+}} = load <4 x double>, <4 x double>* {{%[a-zA-Z0-9_]+}}
// CHECK: [[RES:%[a-zA-Z0-9_]+]] = call spir_func <4 x i32> @_Z12convert_int4Dv4_d(<4 x double> {{%[a-zA-Z0-9_]+}})
// CHECK-GE15: store <4 x i32> [[RES]], ptr [[TO]]
// CHECK-LT15: store <4 x i32> [[RES]], <4 x i32>* [[TO]]
// CHECK: ret void
