// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: spirv-ll-tool -a Vulkan -c Float64 %spv_file_s | FileCheck %s

#version 450

void main() {
  dvec4 a = dvec4(-42.42, -42.42, -42.42, -42.42);
  ivec4 b = ivec4(a);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() #0 {
// CHECK: [[FROM:%[a-zA-Z0-9_]+]] = alloca <4 x double>
// CHECK: [[TO:%[a-zA-Z0-9_]+]] = alloca <4 x i32>
// CHECK: store <4 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr [[FROM]]
// CHECK: {{%[a-zA-Z0-9_]+}} = load <4 x double>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: [[RES:%[a-zA-Z0-9_]+]] = call spir_func <4 x i32> @_Z12convert_int4Dv4_d(<4 x double> {{%[a-zA-Z0-9_]+}})
// CHECK: store <4 x i32> [[RES]], ptr [[TO]]
// CHECK: ret void
