// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan -c Float64 %p/op_convert_dvec3_to_ivec3.spv -o %t
// RUN: %filecheck < %t %t.pp

#version 450

void main() {
  dvec3 a = dvec3(-42.42, -42.42, -42.42);
  ivec3 b = ivec3(a);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: [[FROM:%[a-zA-Z0-9_]+]] = alloca <3 x double>
// CHECK: [[TO:%[a-zA-Z0-9_]+]] = alloca <3 x i32>
// CHECK-GE15: store <3 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr [[FROM]]
// CHECK-LT15: store <3 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, <3 x double>* [[FROM]]
// CHECK-GE15: {{%[a-zA-Z0-9_]+}} = load <3 x double>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK-LT15: {{%[a-zA-Z0-9_]+}} = load <3 x double>, <3 x double>* {{%[a-zA-Z0-9_]+}}
// CHECK: [[RES:%[a-zA-Z0-9_]+]] = call spir_func <3 x i32> @_Z12convert_int3Dv3_d(<3 x double> {{%[a-zA-Z0-9_]+}})
// CHECK-GE15: store <3 x i32> [[RES]], ptr [[TO]]
// CHECK-LT15: store <3 x i32> [[RES]], <3 x i32>* [[TO]]
// CHECK: ret void
