// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan -c Float64 %spv_file_s | FileCheck %s

#version 450

void main() {
  dvec3 a = dvec3(-42.42, -42.42, -42.42);
  ivec3 b = ivec3(a);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() #0 {
// CHECK: [[FROM:%.*]] = alloca <3 x double>
// CHECK: [[TO:%.*]] = alloca <3 x i32>
// CHECK: store <3 x double> {{<(double -4.242000e\+01(, )?)+>|splat \(double -4.242000e\+01\)}}, ptr [[FROM]]
// CHECK: = load <3 x double>, ptr {{%.*}}
// CHECK: [[RES:%.*]] = call spir_func <3 x i32> @_Z12convert_int3Dv3_d(<3 x double> {{%.*}})
// CHECK: store <3 x i32> [[RES]], ptr [[TO]]
// CHECK: ret void
