// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan -c Float64 %p/op_convert_dvec4_to_ivec4.spv | %filecheck %s

#version 450

void main() {
  dvec4 a = dvec4(-42.42, -42.42, -42.42, -42.42);
  ivec4 b = ivec4(a);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: [[FROM:%[a-zA-Z0-9_]+]] = alloca <4 x double>
// CHECK: [[TO:%[a-zA-Z0-9_]+]] = alloca <4 x i32>
// CHECK: store <4 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr [[FROM]]
// CHECK: {{%[a-zA-Z0-9_]+}} = load <4 x double>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: [[RES:%[a-zA-Z0-9_]+]] = call spir_func <4 x i32> @_Z12convert_int4Dv4_d(<4 x double> {{%[a-zA-Z0-9_]+}})
// CHECK: store <4 x i32> [[RES]], ptr [[TO]]
// CHECK: ret void
