// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan -c Float64 %spv_file_s | %filecheck %s

#version 450

void main() {
  dvec2 a = dvec2(-42.42, -42.42);
  ivec2 b = ivec2(a);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: [[FROM:%[a-zA-Z0-9_]+]] = alloca <2 x double>
// CHECK: [[TO:%[a-zA-Z0-9_]+]] = alloca <2 x i32>
// CHECK: store <2 x double> <double -4.242000e+01, double -4.242000e+01>, ptr [[FROM]]
// CHECK: {{%[a-zA-Z0-9_]+}} = load <2 x double>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: [[RES:%[a-zA-Z0-9_]+]] = call spir_func <2 x i32> @_Z12convert_int2Dv2_d(<2 x double> {{%[a-zA-Z0-9_]+}})
// CHECK: store <2 x i32> [[RES]], ptr [[TO]]
// CHECK: ret void
