// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// REQUIRES: arm
// RUN: spirv-ll-tool -a Vulkan -c Float64 %spv_file_s | FileCheck %s

#version 450

void main() {
  double x = -42.42;
  double y = -42.42;
  double res = mod(x, y);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca double
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca double
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca double
// CHECK: store double -4.242000e+01, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: store double -4.242000e+01, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = load double, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = load double, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = call spir_func double @_Z4fmoddd(double {{%[a-zA-Z0-9_]+}}, double {{%[a-zA-Z0-9_]+}})
// CHECK: {{%[a-zA-Z0-9_]+}} = call spir_func double @_Z8copysigndd(double {{%[a-zA-Z0-9_]+}}, double {{%[a-zA-Z0-9_]+}})
// CHECK: store double {{%[a-zA-Z0-9_]+}}, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: ret void
// CHECK: declare spir_func double @_Z8copysigndd(double, double)
