// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// REQUIRES: arm
// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan %p/op_fmod_vec4.spv -o %t
// RUN: %filecheck < %t %t.pp

// CHECK: ; ModuleID = '{{.*}}'
#version 450

void main() {
// CHECK: define spir_kernel void @main() {
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x float>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x float>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x float>
  vec4 x = vec4(42.42, 42.42, 42.42, 42.42);
// CHECK-GE15:  store <4 x float> <float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK-LT15:  store <4 x float> <float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000>, <4 x float>* {{%[a-zA-Z0-9_]+}}
  vec4 y = vec4(42.42, 42.42, 42.42, 42.42);
// CHECK-GE15:  store <4 x float> <float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK-LT15:  store <4 x float> <float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000>, <4 x float>* {{%[a-zA-Z0-9_]+}}
// CHECK-GE15:  [[X:%[a-zA-Z0-9_]+]] = load <4 x float>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK-LT15:  [[X:%[a-zA-Z0-9_]+]] = load <4 x float>, <4 x float>* {{%[a-zA-Z0-9_]+}}
// CHECK-GE15:  [[Y:%[a-zA-Z0-9_]+]] = load <4 x float>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK-LT15:  [[Y:%[a-zA-Z0-9_]+]] = load <4 x float>, <4 x float>* {{%[a-zA-Z0-9_]+}}
  vec4 res = mod(x, y);
// CHECK:  [[MOD:%[a-zA-Z0-9_]+]] = call spir_func <4 x float> @_Z4fmodDv4_fS_(<4 x float> [[X]], <4 x float> [[Y]])
// CHECK:  [[RES:%[a-zA-Z0-9_]+]] = call spir_func <4 x float> @_Z8copysignDv4_fS_(<4 x float> [[MOD]], <4 x float> [[Y]])
// CHECK-GE15:  store <4 x float> [[RES]], ptr {{%[a-zA-Z0-9_]+}}
// CHECK-LT15:  store <4 x float> [[RES]], <4 x float>* {{%[a-zA-Z0-9_]+}}
// CHECK:  ret void
}

// CHECK: declare spir_func <4 x float> @_Z8copysignDv4_fS_(<4 x float>, <4 x float>)
