// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %p/op_function_parameter_bool.spv | %filecheck %s

#version 450

bool foo(bool a, bool b){ 
  return a == b;
}

void main() {
  bool res = foo(true, true);
}

// CHECK: ; ModuleID = '{{.*}}'

// CHECK: define spir_kernel void @main() {
// CHECK: [[res:%[a-zA-Z0-9]+]] = alloca i1
// CHECK: [[param:%[a-zA-Z0-9]+]] = alloca i1
// CHECK: [[param1:%[a-zA-Z0-9]+]] = alloca i1
// CHECK: store i1 true, ptr [[param]]
// CHECK: store i1 true, ptr [[param1]]
// CHECK: [[call:%[a-zA-Z0-9]+]] = call spir_func i1 @{{(foo|"foo\(.+")}}(ptr [[param]], ptr [[param1]])
// CHECK: store i1 [[call]], ptr [[res]]
// CHECK: ret void
// CHECK: }

// CHECK: define private spir_func i1 @{{(foo|"foo\(.+")}}(ptr %a, ptr %b) {
// CHECK: [[a:%[a-zA-Z0-9]+]] = load i1, ptr %a
// CHECK: [[b:%[a-zA-Z0-9]+]] = load i1, ptr %b
// CHECK: [[ret:%[a-zA-Z0-9]+]] = icmp eq i1 [[a]], [[b]]
// CHECK: ret i1 [[ret]]
// CHECK: }
