// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan -c Float64 %spv_file_s | FileCheck %s

#version 450

void main() {
  dmat4x4 a = {
      {-42.42, -42.42, -42.42, -42.42},
      {-42.42, -42.42, -42.42, -42.42},
      {-42.42, -42.42, -42.42, -42.42},
      {-42.42, -42.42, -42.42, -42.42}
  };
  dmat4x4 b = {
      {-42.42, -42.42, -42.42, -42.42},
      {-42.42, -42.42, -42.42, -42.42},
      {-42.42, -42.42, -42.42, -42.42},
      {-42.42, -42.42, -42.42, -42.42}
  };
  dmat4x4 c = a - b;
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main()
// CHECK: = extractvalue [4 x <4 x double>] {{[%@].*}}, 0
// CHECK: = extractvalue [4 x <4 x double>] {{[%@].*}}, 0
// CHECK: = fsub <4 x double> {{[%@].*}}, {{[%@].*}}
// CHECK: = extractvalue [4 x <4 x double>] {{[%@].*}}, 1
// CHECK: = extractvalue [4 x <4 x double>] {{[%@].*}}, 1
// CHECK: = fsub <4 x double> {{[%@].*}}, {{[%@].*}}
// CHECK: = extractvalue [4 x <4 x double>] {{[%@].*}}, 2
// CHECK: = extractvalue [4 x <4 x double>] {{[%@].*}}, 2
// CHECK: = fsub <4 x double> {{[%@].*}}, {{[%@].*}}
// CHECK: = extractvalue [4 x <4 x double>] {{[%@].*}}, 3
// CHECK: = extractvalue [4 x <4 x double>] {{[%@].*}}, 3
// CHECK: = fsub <4 x double> {{[%@].*}}, {{[%@].*}}
// CHECK: [[INITIAL:%.*]] = insertvalue [4 x <4 x double>] undef, <4 x double> {{[%@].*}}, 0
// CHECK: [[INSERT1:%.*]] = insertvalue [4 x <4 x double>] [[INITIAL]], <4 x double> {{[%@].*}}, 1
// CHECK: [[INSERT2:%.*]] = insertvalue [4 x <4 x double>] [[INSERT1]], <4 x double> {{[%@].*}}, 2
// CHECK: = insertvalue [4 x <4 x double>] [[INSERT2]], <4 x double> {{[%@].*}}, 3
// CHECK: ret void
