// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// REQUIRES: WorkingFrem
// RUN: spirv-ll-tool -a Vulkan %spv_file_s | FileCheck %s

// CHECK: ; ModuleID = '{{.*}}'
#version 450

void main() {
// CHECK: define spir_kernel void @main() {
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <2 x float>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <2 x float>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <2 x float>
  vec2 x = vec2(42.42, 42.42);
// CHECK:  store <2 x float> <float 0x404535C280000000, float 0x404535C280000000>, ptr {{%[a-zA-Z0-9_]+}}
  vec2 y = vec2(42.42, 42.42);
// CHECK:  store <2 x float> <float 0x404535C280000000, float 0x404535C280000000>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[X:%[a-zA-Z0-9_]+]] = load <2 x float>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[Y:%[a-zA-Z0-9_]+]] = load <2 x float>, ptr {{%[a-zA-Z0-9_]+}}
  vec2 res = mod(x, y);
// CHECK:  [[MOD:%[a-zA-Z0-9_]+]] = call spir_func <2 x float> @_Z4fmodDv2_fS_(<2 x float> [[X]], <2 x float> [[Y]])
// CHECK:  [[RES:%[a-zA-Z0-9_]+]] = call spir_func <2 x float> @_Z8copysignDv2_fS_(<2 x float> [[MOD]], <2 x float> [[Y]])
// CHECK:  store <2 x float> [[RES]], ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  ret void
}

// CHECK: declare spir_func <2 x float> @_Z8copysignDv2_fS_(<2 x float>, <2 x float>)
