// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan -c Float64 %p/op_function_parameter_double.spv -o %t
// RUN: %filecheck < %t %t.pp

#version 450

bool foo(double a, double b){ 
  return a == b;
}

void main() {
  bool res = foo(-42.42, -42.42);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: [[res:%[a-zA-Z0-9]+]] = alloca i1
// CHECK: [[param:%[a-zA-Z0-9]+]] = alloca double
// CHECK: [[param1:%[a-zA-Z0-9]+]] = alloca double
// CHECK-GE15: store double -4.242000e+01, ptr [[param]]
// CHECK-LT15: store double -4.242000e+01, double* [[param]]
// CHECK-GE15: store double -4.242000e+01, ptr [[param1]]
// CHECK-LT15: store double -4.242000e+01, double* [[param1]]
// CHECK-GE15: [[call:%[a-zA-Z0-9]+]] = call spir_func i1 @{{(foo|"foo\(.+")}}(ptr [[param]], ptr [[param1]])
// CHECK-LT15: [[call:%[a-zA-Z0-9]+]] = call spir_func i1 @{{(foo|"foo\(.+")}}(double* [[param]], double* [[param1]])
// CHECK-GE15: store i1 [[call]], ptr [[res]]
// CHECK-LT15: store i1 [[call]], i1* [[res]]
// CHECK: ret void
// CHECK: }

// CHECK-GE15: define private spir_func i1 @{{(foo|"foo\(.+")}}(ptr %a, ptr %b) {
// CHECK-LT15: define private spir_func i1 @{{(foo|"foo\(.+")}}(double* %a, double* %b) {
// CHECK-GE15: [[a:%[a-zA-Z0-9]+]] = load double, ptr %a
// CHECK-LT15: [[a:%[a-zA-Z0-9]+]] = load double, double* %a
// CHECK-GE15: [[b:%[a-zA-Z0-9]+]] = load double, ptr %b
// CHECK-LT15: [[b:%[a-zA-Z0-9]+]] = load double, double* %b
// CHECK: [[ret:%[a-zA-Z0-9]+]] = fcmp oeq double [[a]], [[b]]
// CHECK: ret i1 [[ret]]
// CHECK: }
