// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan %spv_file_s | FileCheck %s

#version 450

void main() {
  mat3x3 a = {
      {42.42, 42.42, 42.42},
      {42.42, 42.42, 42.42},
      {42.42, 42.42, 42.42}
  };
  mat3x3 b = {
      {42.42, 42.42, 42.42},
      {42.42, 42.42, 42.42},
      {42.42, 42.42, 42.42}
  };
  mat3x3 c = a / b;
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main()
// CHECK: = extractvalue [3 x <3 x float>] {{[%@].*}}, 0
// CHECK: = extractvalue [3 x <3 x float>] {{[%@].*}}, 0
// CHECK: = fdiv <3 x float> {{[%@].*}}, {{[%@].*}}
// CHECK: = extractvalue [3 x <3 x float>] {{[%@].*}}, 1
// CHECK: = extractvalue [3 x <3 x float>] {{[%@].*}}, 1
// CHECK: = fdiv <3 x float> {{[%@].*}}, {{[%@].*}}
// CHECK: = extractvalue [3 x <3 x float>] {{[%@].*}}, 2
// CHECK: = extractvalue [3 x <3 x float>] {{[%@].*}}, 2
// CHECK: = fdiv <3 x float> {{[%@].*}}, {{[%@].*}}
// CHECK: [[INITIAL:%.*]] = insertvalue [3 x <3 x float>] undef, <3 x float> {{[%@].*}}, 0
// CHECK: [[INSERT1:%.*]] = insertvalue [3 x <3 x float>] [[INITIAL]], <3 x float> {{[%@].*}}, 1
// CHECK: = insertvalue [3 x <3 x float>] [[INSERT1]], <3 x float> {{[%@].*}}, 2
// CHECK: ret void
