// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

#version 450

void main() {
  mat2x2 a = {
      {42.42, 42.42},
      {42.42, 42.42}
  };
  mat2x2 b = {
      {42.42, 42.42},
      {42.42, 42.42}
  };
  mat2x2 c = a - b;
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main()
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [2 x <2 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 0
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [2 x <2 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 0
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = fsub <2 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [2 x <2 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 1
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = extractvalue [2 x <2 x float>] {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 1
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = fsub <2 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: [[INITIAL:%[a-zA-Z0-9_]+]] = insertvalue [2 x <2 x float>] undef, <2 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 0
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = insertvalue [2 x <2 x float>] [[INITIAL]], <2 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, 1
// CHECK: ret void
