// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// REQUIRES: arm
// RUN: %spirv-ll -a Vulkan -c Float64 %p/op_fmod_dvec3.spv | %filecheck %s

// CHECK: ; ModuleID = '{{.*}}'
#version 450

void main() {
// CHECK: define spir_kernel void @main() {
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <3 x double>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <3 x double>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <3 x double>
  dvec3 x = dvec3(-42.42, -42.42, -42.42);
// CHECK:  store <3 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr {{%[a-zA-Z0-9_]+}}
  dvec3 y = dvec3(-42.42, -42.42, -42.42);
// CHECK:  store <3 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[X:%[a-zA-Z0-9_]+]] = load <3 x double>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[Y:%[a-zA-Z0-9_]+]] = load <3 x double>, ptr {{%[a-zA-Z0-9_]+}}
  dvec3 res = mod(x, y);
// CHECK:  [[MOD:%[a-zA-Z0-9_]+]] = call spir_func <3 x double> @_Z4fmodDv3_dS_(<3 x double> [[X]], <3 x double> [[Y]])
// CHECK:  [[RES:%[a-zA-Z0-9_]+]] = call spir_func <3 x double> @_Z8copysignDv3_dS_(<3 x double> [[MOD]], <3 x double> [[Y]])
// CHECK:  store <3 x double> [[RES]], ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  ret void
}

// CHECK: declare spir_func <3 x double> @_Z8copysignDv3_dS_(<3 x double>, <3 x double>)
