// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// REQUIRES: arm
// RUN: %spirv-ll -a Vulkan -c Float64 %spv_file_s | %filecheck %s

// CHECK: ; ModuleID = '{{.*}}'
#version 450

void main() {
// CHECK: define spir_kernel void @main() {
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x double>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x double>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x double>
  dvec4 x = dvec4(-42.42, -42.42, -42.42, -42.42);
// CHECK:  store <4 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr {{%[a-zA-Z0-9_]+}}
  dvec4 y = dvec4(-42.42, -42.42, -42.42, -42.42);
// CHECK:  store <4 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[X:%[a-zA-Z0-9_]+]] = load <4 x double>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[Y:%[a-zA-Z0-9_]+]] = load <4 x double>, ptr {{%[a-zA-Z0-9_]+}}
  dvec4 res = mod(x, y);
// CHECK:  [[MOD:%[a-zA-Z0-9_]+]] = call spir_func <4 x double> @_Z4fmodDv4_dS_(<4 x double> [[X]], <4 x double> [[Y]])
// CHECK:  [[RES:%[a-zA-Z0-9_]+]] = call spir_func <4 x double> @_Z8copysignDv4_dS_(<4 x double> [[MOD]], <4 x double> [[Y]])
// CHECK:  store <4 x double> [[RES]], ptr %res
// CHECK:  ret void
}

// CHECK: declare spir_func <4 x double> @_Z8copysignDv4_dS_(<4 x double>, <4 x double>)
