// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// REQUIRES: WorkingFrem
// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: spirv-ll-tool -a Vulkan -c Float64 %spv_file_s | FileCheck %s

// CHECK: ; ModuleID = '{{.*}}'
#version 450

void main() {
// CHECK: define spir_kernel void @main() #0 {
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x double>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x double>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <4 x double>
  dvec4 x = dvec4(-42.42, -42.42, -42.42, -42.42);
// CHECK:  store <4 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr {{%[a-zA-Z0-9_]+}}
  dvec4 y = dvec4(-42.42, -42.42, -42.42, -42.42);
// CHECK:  store <4 x double> <double -4.242000e+01, double -4.242000e+01, double -4.242000e+01, double -4.242000e+01>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[X:%[a-zA-Z0-9_]+]] = load <4 x double>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[Y:%[a-zA-Z0-9_]+]] = load <4 x double>, ptr {{%[a-zA-Z0-9_]+}}
  dvec4 res = mod(x, y);
// CHECK:  [[MOD:%[a-zA-Z0-9_]+]] = call spir_func <4 x double> @_Z4fmodDv4_dS_(<4 x double> [[X]], <4 x double> [[Y]])
// CHECK:  [[RES:%[a-zA-Z0-9_]+]] = call spir_func <4 x double> @_Z8copysignDv4_dS_(<4 x double> [[MOD]], <4 x double> [[Y]])
// CHECK:  store <4 x double> [[RES]], ptr %res
// CHECK:  ret void
}

// CHECK: declare spir_func <4 x double> @_Z8copysignDv4_dS_(<4 x double>, <4 x double>)
