// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// REQUIRES: WorkingFrem
// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan %spv_file_s | FileCheck %s

// CHECK: ; ModuleID = '{{.*}}'
#version 450

void main() {
// CHECK: define spir_kernel void @main() #0 {
// CHECK:  {{%.*}} = alloca <4 x float>
// CHECK:  {{%.*}} = alloca <4 x float>
// CHECK:  {{%.*}} = alloca <4 x float>
  vec4 x = vec4(42.42, 42.42, 42.42, 42.42);
// CHECK:  store <4 x float> <float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000>, ptr {{%.*}}
  vec4 y = vec4(42.42, 42.42, 42.42, 42.42);
// CHECK:  store <4 x float> <float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000>, ptr {{%.*}}
// CHECK:  [[X:%.*]] = load <4 x float>, ptr {{%.*}}
// CHECK:  [[Y:%.*]] = load <4 x float>, ptr {{%.*}}
  vec4 res = mod(x, y);
// CHECK:  [[MOD:%.*]] = call spir_func <4 x float> @_Z4fmodDv4_fS_(<4 x float> [[X]], <4 x float> [[Y]])
// CHECK:  [[RES:%.*]] = call spir_func <4 x float> @_Z8copysignDv4_fS_(<4 x float> [[MOD]], <4 x float> [[Y]])
// CHECK:  store <4 x float> [[RES]], ptr {{%.*}}
// CHECK:  ret void
}

// CHECK: declare spir_func <4 x float> @_Z8copysignDv4_fS_(<4 x float>, <4 x float>)
