// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// REQUIRES: WorkingFrem
// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

#version 450

void main() {
  float x = 42.42;
  float y = 42.42;
  float res = mod(x, y);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca float
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca float
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca float
// CHECK: store float 0x404535C280000000, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: store float 0x404535C280000000, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = load float, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = load float, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = call spir_func float @_Z4fmodff(float %1, float %2)
// CHECK: {{%[a-zA-Z0-9_]+}} = call spir_func float @_Z8copysignff(float {{%[a-zA-Z0-9_]+}}, float {{%[a-zA-Z0-9_]+}})
// CHECK: store float {{%[a-zA-Z0-9_]+}}, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: ret void
// CHECK: declare spir_func float @_Z8copysignff(float, float)
