// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// REQUIRES: arm
// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

// CHECK: ; ModuleID = '{{.*}}'
#version 450

void main() {
// CHECK: define spir_kernel void @main() {
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <3 x float>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <3 x float>
// CHECK:  {{%[a-zA-Z0-9_]+}} = alloca <3 x float>
  vec3 x = vec3(42.42, 42.42, 42.42);
// CHECK:  store <3 x float> <float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000>, ptr {{%[a-zA-Z0-9_]+}}
  vec3 y = vec3(42.42, 42.42, 42.42);
// CHECK:  store <3 x float> <float 0x404535C280000000, float 0x404535C280000000, float 0x404535C280000000>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[X:%[a-zA-Z0-9_]+]] = load <3 x float>, ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  [[Y:%[a-zA-Z0-9_]+]] = load <3 x float>, ptr {{%[a-zA-Z0-9_]+}}
  vec3 res = mod(x, y);
// CHECK:  [[MOD:%[a-zA-Z0-9_]+]] = call spir_func <3 x float> @_Z4fmodDv3_fS_(<3 x float> [[X]], <3 x float> [[Y]])
// CHECK:  [[RES:%[a-zA-Z0-9_]+]] = call spir_func <3 x float> @_Z8copysignDv3_fS_(<3 x float> [[MOD]], <3 x float> [[Y]])
// CHECK:  store <3 x float> [[RES]], ptr {{%[a-zA-Z0-9_]+}}
// CHECK:  ret void
}

// CHECK: declare spir_func <3 x float> @_Z8copysignDv3_fS_(<3 x float>, <3 x float>)
