// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// REQUIRES: WorkingFrem
// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan -c Float64 %spv_file_s | FileCheck %s

#version 450

void main() {
  double x = -42.42;
  double y = -42.42;
  double res = mod(x, y);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() #0 {
// CHECK: = alloca double
// CHECK: = alloca double
// CHECK: = alloca double
// CHECK: store double -4.242000e+01, ptr {{%.*}}
// CHECK: store double -4.242000e+01, ptr {{%.*}}
// CHECK: = load double, ptr {{%.*}}
// CHECK: = load double, ptr {{%.*}}
// CHECK: = call spir_func double @_Z4fmoddd(double {{%.*}}, double {{%.*}}
// CHECK: = call spir_func double @_Z8copysigndd(double {{%.*}}, double {{%.*}})
// CHECK: store double {{%.*}}, ptr {{%.*}}
// CHECK: ret void
// CHECK: declare spir_func double @_Z8copysigndd(double, double)
