// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan -c Float64 %spv_file_s | %filecheck %s

#version 450

bool foo(double a, double b){ 
  return a == b;
}

void main() {
  bool res = foo(-42.42, -42.42);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: [[res:%[a-zA-Z0-9]+]] = alloca i1
// CHECK: [[param:%[a-zA-Z0-9]+]] = alloca double
// CHECK: [[param1:%[a-zA-Z0-9]+]] = alloca double
// CHECK: store double -4.242000e+01, ptr [[param]]
// CHECK: store double -4.242000e+01, ptr [[param1]]
// CHECK: [[call:%[a-zA-Z0-9]+]] = call spir_func i1 @{{(foo|"foo\(.+")}}(ptr [[param]], ptr [[param1]])
// CHECK: store i1 [[call]], ptr [[res]]
// CHECK: ret void
// CHECK: }

// CHECK: define private spir_func i1 @{{(foo|"foo\(.+")}}(ptr %a, ptr %b) {
// CHECK: [[a:%[a-zA-Z0-9]+]] = load double, ptr %a
// CHECK: [[b:%[a-zA-Z0-9]+]] = load double, ptr %b
// CHECK: [[ret:%[a-zA-Z0-9]+]] = fcmp oeq double [[a]], [[b]]
// CHECK: ret i1 [[ret]]
// CHECK: }
