// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// REQUIRES: WorkingFrem
// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

#version 450

void main() {
  float x = 42.42;
  float y = 42.42;
  float res = mod(x, y);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca float
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca float
// CHECK: {{%[a-zA-Z0-9_]+}} = alloca float
// CHECK: store float 0x404535C280000000, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: store float 0x404535C280000000, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = load float, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = load float, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: {{%[a-zA-Z0-9_]+}} = call spir_func float @_Z4fmodff(float %1, float %2)
// CHECK: {{%[a-zA-Z0-9_]+}} = call spir_func float @_Z8copysignff(float {{%[a-zA-Z0-9_]+}}, float {{%[a-zA-Z0-9_]+}})
// CHECK: store float {{%[a-zA-Z0-9_]+}}, ptr {{%[a-zA-Z0-9_]+}}
// CHECK: ret void
// CHECK: declare spir_func float @_Z8copysignff(float, float)
