// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %pp-llvm-ver -o %t.pp < %s --llvm-ver %LLVMVER
// RUN: %spirv-ll -a Vulkan %p/op_function_parameter_int.spv -o %t
// RUN: %filecheck < %t %t.pp

#version 450

bool foo(int a, int b){ 
  return a == b;
}

void main() {
  bool res = foo(-42, -42);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() {
// CHECK: [[res:%[a-zA-Z0-9]+]] = alloca i1
// CHECK: [[param:%[a-zA-Z0-9]+]] = alloca i32
// CHECK: [[param1:%[a-zA-Z0-9]+]] = alloca i32
// CHECK-GE15: store i32 -42, ptr [[param]]
// CHECK-LT15: store i32 -42, i32* [[param]]
// CHECK-GE15: store i32 -42, ptr [[param1]]
// CHECK-LT15: store i32 -42, i32* [[param1]]
// CHECK-GE15: [[call:%[a-zA-Z0-9]+]] = call spir_func i1 @{{(foo|"foo\(.+")}}(ptr [[param]], ptr [[param1]])
// CHECK-LT15: [[call:%[a-zA-Z0-9]+]] = call spir_func i1 @{{(foo|"foo\(.+")}}(i32* [[param]], i32* [[param1]])
// CHECK-GE15: store i1 [[call]], ptr [[res]]
// CHECK-LT15: store i1 [[call]], i1* [[res]]
// CHECK: ret void
// CHECK: }

// CHECK-GE15: define private spir_func i1 @{{(foo|"foo\(.+")}}(ptr %a, ptr %b) {
// CHECK-LT15: define private spir_func i1 @{{(foo|"foo\(.+")}}(i32* %a, i32* %b) {
// CHECK-GE15: [[a:%[a-zA-Z0-9]+]] = load i32, ptr %a
// CHECK-LT15: [[a:%[a-zA-Z0-9]+]] = load i32, i32* %a
// CHECK-GE15: [[b:%[a-zA-Z0-9]+]] = load i32, ptr %b
// CHECK-LT15: [[b:%[a-zA-Z0-9]+]] = load i32, i32* %b
// CHECK: [[ret:%[a-zA-Z0-9]+]] = icmp eq i32 [[a]], [[b]]
// CHECK: ret i1 [[ret]]
// CHECK: }
