// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

#version 450

layout (std430, set=0, binding=0) buffer inA {
  uvec3 arg0;
  uvec3 arg1;
  uvec3 arg2;
};

layout (std430, set=0, binding=1) buffer outR {
  uvec3 res;
};

void main() {
  res = clamp(arg0,arg1,arg2);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <3 x i32>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <3 x i32>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <3 x i32>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = call spir_func <3 x i32> @_Z5clampDv3_jS_S_(<3 x i32> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, <3 x i32> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, <3 x i32> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}})
// CHECK: store <3 x i32> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: ret void
// CHECK: declare spir_func <3 x i32> @_Z5clampDv3_jS_S_(<3 x i32>, <3 x i32>, <3 x i32>)
