// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan -c Float64 %p/op_glsl_FMix_dvec2_dvec2_dvec2.spv | %filecheck %s

#version 450

layout (std430, set=0, binding=0) buffer inA {
  dvec2 arg0;
  dvec2 arg1;
  dvec2 arg2;
};

layout (std430, set=0, binding=1) buffer outR {
  dvec2 res;
};

void main() {
  res = mix(arg0,arg1,arg2);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <2 x double>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <2 x double>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <2 x double>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = call spir_func <2 x double> @_Z3mixDv2_dS_S_(<2 x double> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, <2 x double> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, <2 x double> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}})
// CHECK: store <2 x double> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: ret void
// CHECK: declare spir_func <2 x double> @_Z3mixDv2_dS_S_(<2 x double>, <2 x double>, <2 x double>)
