// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan %spv_file_s | FileCheck %s

#version 450

layout (std430, set=0, binding=0) buffer inA {
  vec2 arg0;
};

layout (std430, set=0, binding=1) buffer outR {
  vec2 res;
};

void main() {
  res = degrees(arg0);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: = load <2 x float>, ptr addrspace({{[0-9]}}) {{[%@].*}}
// CHECK: = call spir_func <2 x float> @_Z7degreesDv2_f(<2 x float> {{[%@].*}})
// CHECK: store <2 x float> {{[%@].*}}, ptr addrspace({{[0-9]}}) {{[%@].*}}
// CHECK: ret void
// CHECK: declare spir_func <2 x float> @_Z7degreesDv2_f(<2 x float>)
