// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan -c Float64 %spv_file_s | %filecheck %s

#version 450

layout (std430, set=0, binding=0) buffer inA {
  dvec2 arg0;
};

layout (std430, set=0, binding=1) buffer outR {
  dvec2 res;
};

void main() {
  res = normalize(arg0);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <2 x double>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = call spir_func <2 x double> @_Z9normalizeDv2_d(<2 x double> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}})
// CHECK: store <2 x double> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: ret void
// CHECK: declare spir_func <2 x double> @_Z9normalizeDv2_d(<2 x double>)
