// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

#version 450

layout (std430, set=0, binding=0) buffer inA {
  ivec2 arg0;
};

layout (std430, set=0, binding=1) buffer outR {
  ivec2 res;
};

void main() {
  res = sign(arg0);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <2 x i32>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = call spir_func <2 x i32> @_Z5clampDv2_iS_S_(<2 x i32> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, <2 x i32> <i32 -1, i32 -1>, <2 x i32> <i32 1, i32 1>)
