// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan -c Float64 %p/op_glsl_PackDouble2x32_uvec2.spv | %filecheck %s

#version 450

layout (std430, set=0, binding=0) buffer inA {
  uvec2 arg0;
};

layout (std430, set=0, binding=1) buffer outR {
  double res;
};

void main() {
  res = packDouble2x32(arg0);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <2 x i32>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = bitcast <2 x i32> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} to double
