// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %spv_file_s | %filecheck %s

#version 450

layout (std430, set=0, binding=0) buffer inA {
  int arg0;
};

layout (std430, set=0, binding=1) buffer outR {
  int res;
};

void main() {
  res = sign(arg0);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load i32, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = call spir_func i32 @_Z5clampiii(i32 {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, i32 -1, i32 1)
