// Copyright (C) Codeplay Software Limited. All Rights Reserved.

// RUN: %spirv-ll -a Vulkan %p/op_glsl_Distance_vec4_vec4.spv | %filecheck %s

#version 450

layout (std430, set=0, binding=0) buffer inA {
  vec4 arg0;
  vec4 arg1;
};

layout (std430, set=0, binding=1) buffer outR {
  float res;
};

void main() {
  res = distance(arg0,arg1);
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <4 x float>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = load <4 x float>, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}} = call spir_func float @_Z8distanceDv4_fS_(<4 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, <4 x float> {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}})
// CHECK: store float {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}, ptr addrspace({{[0-9]}}) {{[%@][-a-zA-Z$._0-9][-a-zA-Z$._0-9]*}}
// CHECK: ret void
// CHECK: declare spir_func float @_Z8distanceDv4_fS_(<4 x float>, <4 x float>)
