// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool -a Vulkan %spv_file_s | FileCheck %s

#version 450

void main() {
  uvec2 a = uvec2(42, 42);
  uint b = 42;
  uvec2 c = a / b;
}

// CHECK: ; ModuleID = '{{.*}}'
// CHECK: define spir_kernel void @main() #0 {
// CHECK: = alloca <2 x i32>
// CHECK: = alloca i32
// CHECK: = alloca <2 x i32>
// CHECK: store <2 x i32> {{<(i32 42(, )?)+>|splat \(i32 42\)}}, ptr {{[%@].*}}
// CHECK: store i32 42, ptr {{[%@].*}}
// CHECK: = load <2 x i32>, ptr {{[%@].*}}
// CHECK: = load i32, ptr {{[%@].*}}
// CHECK: = insertelement <2 x i32> undef, i32 {{[%@].*}}, {{i[0-9]+}} {{[0-9]+}}
// CHECK: = insertelement <2 x i32> {{[%@].*}}, i32 {{[%@].*}}, {{i[0-9]+}} {{[0-9]+}}
// CHECK: = udiv <2 x i32> {{[%@].*}}, {{[%@].*}}
// CHECK: store <2 x i32> {{[%@].*}}, ptr {{[%@].*}}
// CHECK: ret void
