// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// RUN: %if online-glsl %{ glslangValidator -s -V -o %spv_file_s %s %}
// RUN: %if online-glsl %{ spirv-val %spv_file_s %}
// RUN: spirv-ll-tool --spec-constants %spv_file_s | FileCheck %s

#version 450

layout (constant_id = 0) const bool constBool = true;
// CHECK: SpecId: 0	OpTypeBool	1 bit
layout (constant_id = 1) const int constInt = 42;
// CHECK: SpecId: 1	OpTypeInt	32 bit
layout (constant_id = 2) const float constFloat = 42.0f;
// CHECK: SpecId: 2	OpTypeFloat	32 bit

void main() {}
