FROM ubuntu:22.04@sha256:4e0171b9275e12d375863f2b3ae9ce00a4c53ddda176bd55868df97ac6f21a6e

RUN apt-get update 
RUN apt-get install -y wget git build-essential

# Enable ability to install foreign packages for cross compilation
RUN dpkg --add-architecture i386
RUN dpkg --add-architecture arm64
RUN dpkg --add-architecture riscv64

# The main archive only hosts amd64 and i386, we need to add ports for arm64 and riscv64.
RUN sed -i -e '/^deb /{h;s|deb |&[arch=amd64,i386] |p;g;s|deb http://[^ ]*|deb [arch=arm64,riscv64] http://ports.ubuntu.com/ubuntu-ports|p;d}' /etc/apt/sources.list

RUN apt-get update

# Add llvm key
RUN wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor - | tee /usr/share/keyrings/llvm-archive-keyring.gpg >/dev/null

# Install minimum requirements
RUN apt-get install --yes cmake libtinfo-dev
# Install 32-bit requirements
RUN apt-get install --yes gcc-multilib g++-multilib libc6-dev:i386 lib32tinfo-dev lib32ncurses-dev
# Install AArch64 requirements
RUN apt-get install --yes gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
# Install RISC-V requirements
RUN apt-get install --yes gcc-riscv64-linux-gnu g++-riscv64-linux-gnu
# Install recommended packages
RUN apt-get install --yes python3 python3-pip ninja-build
# Install CI utility packages
# Install pkg-config for dpc++ builds and locally built spir-v
RUN apt-get install --yes pkg-config
# Install spirv tools
RUN apt-get install --yes spirv-tools

# Install python packages
RUN pip install colorama lit virtualenv

# Install libhwloc-dev for dpc++ dependency
RUN apt-get install --yes libhwloc-dev:amd64 libhwloc-dev:arm64 libhwloc-dev:i386 libhwloc-dev:riscv64

RUN apt-get -y install sudo
RUN apt-get -y install gh
RUN apt install -y zstd
RUN apt install -y gcc g++
RUN apt install -y ccache
