FROM ubuntu:22.04@sha256:4e0171b9275e12d375863f2b3ae9ce00a4c53ddda176bd55868df97ac6f21a6e

RUN apt-get update
RUN apt-get -y install sudo
RUN apt-get install -y git
RUN apt-get install --yes cmake
RUN apt-get install --yes gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
RUN apt-get install --yes python3 python3-pip ninja-build
RUN pip install cmakelint colorama lit
RUN apt-get install --yes spirv-tools
RUN apt-get install --yes wget gpg
RUN wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor - | tee /usr/share/keyrings/llvm-archive-keyring.gpg >/dev/null

RUN apt-get install --yes zstd
RUN apt-get install --yes libhwloc-dev
RUN apt-get -y install gh
