LIBRARY ${ExportLibraryName}
EXPORTS
  vk_icdNegotiateLoaderICDInterfaceVersion
  vk_icdGetInstanceProcAddr
  vkCreateInstance
  vkDestroyInstance
  vkEnumeratePhysicalDevices
  vkGetPhysicalDeviceFeatures
  vkGetPhysicalDeviceFeatures2
  vkGetPhysicalDeviceFormatProperties
  vkGetPhysicalDeviceFormatProperties2
  vkGetPhysicalDeviceImageFormatProperties
  vkGetPhysicalDeviceImageFormatProperties2
  vkGetPhysicalDeviceProperties
  vkGetPhysicalDeviceProperties2
  vkGetPhysicalDeviceQueueFamilyProperties
  vkGetPhysicalDeviceQueueFamilyProperties2
  vkGetPhysicalDeviceMemoryProperties
  vkGetPhysicalDeviceMemoryProperties2
  vkGetInstanceProcAddr
  vkGetDeviceProcAddr
  vkCreateDevice
  vkDestroyDevice
  vkEnumerateInstanceExtensionProperties
  vkEnumerateDeviceExtensionProperties
  vkEnumerateInstanceLayerProperties
  vkEnumerateDeviceLayerProperties
  vkGetDeviceQueue
  vkQueueSubmit
  vkQueueWaitIdle
  vkDeviceWaitIdle
  vkAllocateMemory
  vkFreeMemory
  vkMapMemory
  vkUnmapMemory
  vkFlushMappedMemoryRanges
  vkInvalidateMappedMemoryRanges
  vkGetDeviceMemoryCommitment
  vkBindBufferMemory
  vkBindImageMemory
  vkGetBufferMemoryRequirements
  vkGetImageMemoryRequirements
  vkGetImageSparseMemoryRequirements
  vkGetPhysicalDeviceSparseImageFormatProperties
  vkGetPhysicalDeviceSparseImageFormatProperties2
  vkQueueBindSparse
  vkCreateFence
  vkDestroyFence
  vkResetFences
  vkGetFenceStatus
  vkWaitForFences
  vkCreateSemaphore
  vkDestroySemaphore
  vkCreateEvent
  vkDestroyEvent
  vkGetEventStatus
  vkSetEvent
  vkResetEvent
  vkCreateQueryPool
  vkDestroyQueryPool
  vkGetQueryPoolResults
  vkCreateBuffer
  vkDestroyBuffer
  vkCreateBufferView
  vkDestroyBufferView
  vkCreateImage
  vkDestroyImage
  vkGetImageSubresourceLayout
  vkCreateImageView
  vkDestroyImageView
  vkCreateShaderModule
  vkDestroyShaderModule
  vkCreatePipelineCache
  vkDestroyPipelineCache
  vkGetPipelineCacheData
  vkMergePipelineCaches
  vkCreateGraphicsPipelines
  vkCreateComputePipelines
  vkDestroyPipeline
  vkCreatePipelineLayout
  vkDestroyPipelineLayout
  vkCreateSampler
  vkDestroySampler
  vkCreateDescriptorSetLayout
  vkDestroyDescriptorSetLayout
  vkCreateDescriptorPool
  vkDestroyDescriptorPool
  vkResetDescriptorPool
  vkAllocateDescriptorSets
  vkFreeDescriptorSets
  vkUpdateDescriptorSets
  vkCreateFramebuffer
  vkDestroyFramebuffer
  vkCreateRenderPass
  vkDestroyRenderPass
  vkGetRenderAreaGranularity
  vkCreateCommandPool
  vkDestroyCommandPool
  vkResetCommandPool
  vkAllocateCommandBuffers
  vkFreeCommandBuffers
  vkBeginCommandBuffer
  vkEndCommandBuffer
  vkResetCommandBuffer
  vkCmdBindPipeline
  vkCmdSetViewport
  vkCmdSetScissor
  vkCmdSetLineWidth
  vkCmdSetDepthBias
  vkCmdSetBlendConstants
  vkCmdSetDepthBounds
  vkCmdSetStencilCompareMask
  vkCmdSetStencilWriteMask
  vkCmdSetStencilReference
  vkCmdBindDescriptorSets
  vkCmdBindIndexBuffer
  vkCmdBindVertexBuffers
  vkCmdDraw
  vkCmdDrawIndexed
  vkCmdDrawIndirect
  vkCmdDrawIndexedIndirect
  vkCmdDispatch
  vkCmdDispatchIndirect
  vkCmdCopyBuffer
  vkCmdCopyImage
  vkCmdBlitImage
  vkCmdCopyBufferToImage
  vkCmdCopyImageToBuffer
  vkCmdUpdateBuffer
  vkCmdFillBuffer
  vkCmdClearColorImage
  vkCmdClearDepthStencilImage
  vkCmdClearAttachments
  vkCmdResolveImage
  vkCmdSetEvent
  vkCmdResetEvent
  vkCmdWaitEvents
  vkCmdPipelineBarrier
  vkCmdBeginQuery
  vkCmdEndQuery
  vkCmdResetQueryPool
  vkCmdWriteTimestamp
  vkCmdCopyQueryPoolResults
  vkCmdPushConstants
  vkCmdBeginRenderPass
  vkCmdNextSubpass
  vkCmdEndRenderPass
  vkCmdExecuteCommands
