# Simple workflow for building sccache for PR testing
name: Build cache for PR testing
# Note this will currently create a new sscache file and this must be manually pruned until such time as we have a job
# for this.
on:
  # Uncomment to test this path on a pull request
  # pull_request:
  #   paths:
  #     - '.github/workflows/build_pr_cache.yml'
  #     - '.github/do_build_ock/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build_pr_cache.yml'
      - '.github/actions/do_build_ock/**'
      - '.github/actions/setup_ubuntu_build/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:

  build_pr_ock:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # installs tools, ninja and installs llvm (default 17, RelAssert) and sets up cache
      - name: setup-ubuntu
        uses:  ./.github/actions/setup_ubuntu_build
        with:
          save: true
          llvm_version: 18
          llvm_build_type: RelAssert

      - name: build host x86_64 release
        uses: ./.github/actions/do_build_ock
        with:
          build_type: Release
          build_targets:

      - name: build host x86_64 offline
        uses: ./.github/actions/do_build_ock
        with:
          build_type: Release
          extra_flags: -DCA_RUNTIME_COMPILER_ENABLED=OFF -DCA_EXTERNAL_CLC=${{ github.workspace }}/build/bin/clc
          build_dir: build_offline
          assemble_spirv_ll_lit_test_offline: ON
          build_targets:

      - name: clean_build
        run:
          rm -rf ${{ github.workspace }}/build*

      - name: build riscv m1
        uses: ./.github/actions/do_build_ock/do_build_m1
