name: build opencl cts
description: build opencl cts

inputs:
  target:
    description: 'target architecture'

runs:
  # We don't want a new docker just a list of steps, so mark as composite
  using: "composite"
  steps:
    - name: calc vars
      id: calc_vars
      uses: ./.github/actions/calc_vars
      with:
        target: ${{ inputs.target }}

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main # TODO: use commit hash
    
    - name: download icd artifact
      uses: actions/download-artifact@v4
      with:
        name: icd_${{inputs.target}}
        path: install_icd

    - name: download header artifact
      uses: actions/download-artifact@v4
      with:
        name: header_${{inputs.target}}
        path: install_headers

    - name: build opencl cts
      shell: bash    
      run: |
        # TODO: use formal checkout
        git -c advice.detachedHead=false clone https://github.com/KhronosGroup/OpenCL-CTS --single-branch --depth 1
        cd OpenCL-CTS
        git log -1
        # Ignore patches for now
        #git apply $CI_PROJECT_DIR/patches/OpenCL-CTS-0001-Patch-sub-group-testing.patch
        #git apply $CI_PROJECT_DIR/patches/OpenCL-CTS-0002-Permit-building-for-unknown-architectures.patch
        cd ..
        ls -l *
        #cd $CI_PROJECT_DIR/OpenCL-CTS
        #cmake -G Ninja $CMAKE_TOOLCHAIN $CI_PROJECT_DIR/build/OpenCL-CTS "-DCMAKE_BUILD_TYPE=$CTS_BUILD_TYPE" -DOPENCL_LIBRARIES=OpenCL "-DCL_INCLUDE_DIR=$CI_PROJECT_DIR/OpenCL-CTS/include" "-DCL_LIB_DIR=$CI_PROJECT_DIR/OpenCL-CTS/lib"
        export CTS_BUILD_TYPE=Release
        # used by cmake ??
        export OPENCL_HEADERS_PATH=$GITHUB_WORKSPACE/install_headers
        export ICD_LOADER_INSTALL_PATH=$GITHUB_WORKSPACE/install_icd
        # simulate toolchain data for now
        export TOOLCHAIN="-DCMAKE_C_COMPILER=gcc -DCMAKE_C_FLAGS=-m64 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS=-m64 -DPKG_CONFIG_EXECUTABLE=pkg-config"
        cd $GITHUB_WORKSPACE/install_headers
        echo cmake -G Ninja $TOOLCHAIN $GITHUB_WORKSPACE/OpenCL-CTS "-DCMAKE_BUILD_TYPE=$CTS_BUILD_TYPE" -DOPENCL_LIBRARIES=OpenCL "-DCL_INCLUDE_DIR=$GITHUB_WORKSPACE/install_headers/include" "-DCL_LIB_DIR=$GITHUB_WORKSPACE/install_icd/lib"
        cmake -G Ninja $TOOLCHAIN $GITHUB_WORKSPACE/OpenCL-CTS "-DCMAKE_BUILD_TYPE=$CTS_BUILD_TYPE" -DOPENCL_LIBRARIES=OpenCL "-DCL_INCLUDE_DIR=$GITHUB_WORKSPACE/install_headers/include" "-DCL_LIB_DIR=$GITHUB_WORKSPACE/install_icd/lib"
        ninja -v

        # dummy artefact
        mkdir $GITHUB_WORKSPACE/opencl_cts_dir
        echo Hello > $GITHUB_WORKSPACE/opencl_cts_dir/artefact

    - name: upload opencl cts artifact
      uses: actions/upload-artifact@v4
      with:
        name: opencl_cts_${{inputs.target}}
        path: opencl_cts_dir
        retention-days: 1

